### ISSUE TITLE
Should scope name ( as ID) have max length ?

### ISSUE THREAD

**Issue by MienDev** [IdentityServer/IdentityServer4.EntityFramework#1]
Hello, guys, thanks for your effort on "IdentityServer4.EntityFramework", I tasted it some hours ago. 

When I update migrations to database (Localdb)  with the context "ScopeDbContextEx" (which is extended from **ScopeDbContext**), I got the following

**ERROR** 
> **Column 'Scopes.Name' is not the same length or scale as referencing column 'ScopeSecrets.ScopeName' in foreign key 'FK_ScopeSecrets_Scopes_ScopeName'. Columns participating in a foreign key relationship must be defined with the same length and scale.**

I'm not sure it's  a flaw on "IdentityServer4.EntityFramework" or on "Microsoft.EntityFrameworkCore.SqlServer" . but I sure the problem is on 

```c#
// in "ScopeDbContext.cs"
// ...
scope.Property(x => x.Name).HasMaxLength(200).IsRequired();
// ...
```

**My Fix**

> add a explicit foreign key to "SopeName" to  "ScopeClaim" Entity and "ScopeSecret" Entity.
then add "scopeSecret.Property(x => x.ScopeName).HasMaxLength(200);". 

--OR--
> Just  roughly remove ".HasMaxLength(200)" on Scepe.Name

**I wanna know** 
Is it a MUST for Scope.Name having max length? 
Any  solution better for this?

**Comment by scottbrady91** [comment]
Thanks for the heads up. By the way, this package is still under active development and I would not recommend using it until it is released on nuget (there are many things missing and incomplete, such as the above)

**Comment by brockallen** [comment]
To add to what @scottbrady91 said, we're doing lots of changes still to IdSvr4, so these schema here will still be in flux.

**Comment by MienDev** [comment]
@scottbrady91  yeah, thanks, got it. 

---

@brockallen  thanks for your reminder. 
but I can see that IDS4 RC1 has been scheduled to August 31,  that is quite near (even if  a little delay).
I do not want to take IDS3 as an option for now, since my project is long-term and agile. 
Taking a risk, I plan to use IDS4 in my project with a  self-implemented entityframework layer.
Just hope that there would be no breaking changes after RC1.  :)

**Comment by leastprivilege** [comment]
We use Microsofts RRC (redefined RC) model, which guarantees no breaking changes for release candidates ;)

**Comment by senzacionale** [comment]
You can check and use this repo
https://github.com/PivotalAnimal/BlueConcord.IdentityServer.EntityFrameworkCore/tree/master/BlueConcord.IdentityServer.EntityFrameworkCore

**Comment by MienDev** [comment]
@leastprivilege  haha, very nice :)

---

@senzacionale  thanks, I'll have a look. :)

**Comment by PivotalAnimal** [comment]
Max Length is an issue I've brought up in the past. I think it would do good to implement this as constants in the _IS4_ library. That being said, I'm eager to test out this new repo. I assume you are going to shy away from implementing User functionality as before. I think Microsoft Identity is a good solution but there may be better ones. Also, I have received comments asking for Multitenancy. I would like this feature myself but have not as of yet looked into it much.

**Comment by scottbrady91** [comment]
FYI: https://github.com/aspnet/EntityFramework/issues/6449

Seems we'll be releasing with generated int Id's.
