### ISSUE TITLE
No DbContext named 'ConfigurationDbContext' was found - after upgrade to 2.0.0-rc1

### ISSUE THREAD

**Issue by johnxjcheng** [IdentityServer/IdentityServer4.EntityFramework#101]
After upgrade to IdentityServer4.EntityFramework 2.0.0-rc1, the ConfigurationDbContext is not compatible with the one used by version 1.x. So, I tried to migrate or initialize it. Neither worked. The error I got from migrating is: 

Unable to create an object of type 'ConfigurationDbContext'. Add an implementation of IDesignTimeDbContextFactory<ConfigurationDbContext>' to the project, or see https://go.microsoft.com/fwlink/?linkid=851728 for additional patterns supported at design time.

The error I got from running: dotnet ef migrations add InitialConfigurationDb -c ConfigurationDbContext -o Data/Migrations/IdentityServer/ConfigurationDb
is:
No DbContext named 'ConfigurationDbContext' was found.

**Comment by elanderson** [comment]
@johnxjcheng make sure you don't have anything in the Configure function of the Startup class that has database calls in it as that can cause this here. I had the same issue. You can see [this](https://elanderson.net/2017/09/unable-to-create-an-object-of-type-applicationdbcontext-add-an-implementation-of-idesigntimedbcontextfactory/) blog post for more details.

**Comment by johnxjcheng** [comment]
@elanderson , thanks for the reply. It not only solved the database update issue but also introduced me some key points of migrating project Core 1.x to Core 2.0.

**Comment by brockallen** [comment]
All set, then? Can we close?

**Comment by johnxjcheng** [comment]
Yes, you may.
