### ISSUE TITLE
Error: insert clients not found NormalizedClientId column?

### ISSUE THREAD

**Issue by cqkisyouq** [IdentityServer/IdentityServer4.EntityFramework#102]
VALUES
	(
		i.[AbsoluteRefreshTokenLifetime],
		i.[AccessTokenLifetime],
		i.[AccessTokenType],
		i.[AllowAccessTokensViaBrowser],
		i.[AllowOfflineAccess],
		i.[AllowPlainTextPkce],
		i.[AllowRememberConsent],
		i.[AlwaysIncludeUserClaimsInIdToken],
		i.[AlwaysSendClientClaims],
		i.[AuthorizationCodeLifetime],
		i.[BackChannelLogoutSessionRequired],
		i.[BackChannelLogoutUri],
		i.[ClientId],
		i.[ClientName],
		i.[ClientUri],
		i.[ConsentLifetime],
		i.[Description],
		i.[EnableLocalLogin],
		i.[Enabled],
		i.[FrontChannelLogoutSessionRequired],
		i.[FrontChannelLogoutUri],
		i.[IdentityTokenLifetime],
		i.[IncludeJwtId],
		i.[LogoUri],
		i.[NormalizedClientId],
		i.[PrefixClientClaims],
		i.[ProtocolType],
		i.[RefreshTokenExpiration],
		i.[RefreshTokenUsage],
		i.[RequireClientSecret],
		i.[RequireConsent],
		i.[RequirePkce],
		i.[SlidingRefreshTokenLifetime],
		i.[UpdateAccessTokenClaimsOnRefresh]
	) OUTPUT INSERTED.[Id],
	i._Position INTO @inserted0 ;

SELECT
	[t].[Id]
FROM
	[Clients] t
INNER JOIN @inserted0 i ON ([t].[Id] = [i].[Id])
ORDER BY
	[i].[_Position];

**Comment by brockallen** [comment]
This column was removed. When we do our release it won't be there.
