### ISSUE TITLE
Would it be possible to add the foreign key ClientId into Client* Entities

### ISSUE THREAD

**Issue by Jenan** [IdentityServer/IdentityServer4.EntityFramework#103]
Hello,

I have tried to create some `BaseRepository `for entities in this library and if I have tried to update for example entity `ClientScope `- I have to load whole object of `Client` before updating the `ClientScope`.

I have tried this:
```cs
public void UpdateClientScope(ClientScope scope){

_dbContext.ClientScope.Update(scope);
_dbContext.SaveChanges();
}

var scope = new ClientScope() { Client = new Client{Id = 1}, Id = 1, Scope = "Test Scope" }
UpdateClientScope(scope);
```
I want to specify only `ClientId `- not loading whole `Client `object - but in this case is not probable possible because ChangeTracker doesn't know if I want to update only `ClientScope`.

I would like to use something like this:

```cs
public class ClientScope
{
    public int Id { get; set; }

    public string Scope { get; set; }

    public Client Client { get; set; }
    
    public int ClientId { get; set; }
}

modelBuilder.Entity<ClientScope>()
	            .HasOne(p => p.Client)
	            .WithMany(b => b.AllowedScopes)
	            .HasForeignKey(p => p.ClientId)

```

I think in this case I am able do it following:

```cs
public void UpdateClientScope(ClientScope scope){

_dbContext.ClientScope.Update(scope);
_dbContext.SaveChanges();
}

var scope = new ClientScope() { ClientId = 1, Id = 1, Scope = "Test Scope" }
UpdateClientScope(scope);
```

What do you think about it?

Thank you.

**Comment by brockallen** [comment]
Our design is for the two DB contexts to be separate since you might not use both. If you want this, then you'd need your own set of contexts and entities that model those FKs.

**Comment by Jenan** [comment]
But I think you can add this foreign key although if you have separate dbcontexts?

**Comment by Jenan** [comment]
I am wondering about inherit your set of entities and add some extra requirements for specific scenario, but I think the ClientId foreign key would be fine. :)

**Comment by brockallen** [comment]
> But I think you can add this foreign key although if you have separate dbcontexts?

But we have customers where they're using the operational data, but not the configuration data.

**Comment by brockallen** [comment]
As for wanting to provide additional data, then I'd suggest creating separate tables, or use the new Properties collection we've added in 2.0.

**Comment by Jenan** [comment]
OK, it is only for EF update, I don't want to load whole Client entity before Updating relation tables like ClientScopes. I have posted this use case on StackOverflow and I got this recommendation around EF which I mentioned in original question.

**Comment by Jenan** [comment]
My idea is something like this:
public class ClientScope : ClientScope {... add FK }
Install Ids4.EF package for the original model.
What do you think about it?

**Comment by brockallen** [comment]
No idea. If you can make it work the way you want, that's great. I have a feeling it will be a lot of work and I don't see the gain... but you might have your reasons.

**Comment by Jenan** [comment]
Please, take a look: https://stackoverflow.com/questions/46337780/how-update-object-with-relation-data-in-entityframework-core
