### ISSUE TITLE
Migrating IDS4 to different Schema

### ISSUE THREAD

**Issue by simonare** [IdentityServer/IdentityServer4.EntityFramework#106]
Hi,

I am trying to deploy IDS4 Store to SQL Server but instead of using default dbo schema, I am trying to use "ids" named schema. However, It turns out that system throws an exception "Invalid object name 'Clients'."

How can I solve this issue?

**Comment by brockallen** [comment]
Not sure. We now have some EF docs: http://docs.identityserver.io/en/release/reference/ef.html, so perhaps that will help.

**Comment by brockallen** [comment]
All set on this issue? Can we close it?

**Comment by smairo** [comment]
@simonare You can create a new class (eg IdentityServer4ConfigContext) then inherit ConfigurationDbContext and run add-migrations where you change schema to "YourSchema".

When you have done that, you should set options.DefaultSchema = "YourSchema" in startup where you configure .AddConfigurationStore and .AddOperationalStore.

IdentityServer4ConfigContext class
`
    public class IdentityServer4ConfigContext : ConfigurationDbContext
    {
        public IdentityServer4ConfigContext(DbContextOptions<ConfigurationDbContext> options, ConfigurationStoreOptions storeOptions) :
            base(options, storeOptions)
        {
        }
    }
`

Startup.cs:
`
            services.AddIdentityServer()
                .AddDeveloperSigningCredential()
                .AddAspNetIdentity<ApplicationUser>()
                .AddConfigurationStore(options => {
                    options.DefaultSchema = "ServerConfig";
                    options.ConfigureDbContext = builder =>
                        builder.UseSqlServer(_connectionString,
                            sql => sql.MigrationsAssembly(_migrationsAssembly));
                })
                .AddOperationalStore(options => {
                    options.DefaultSchema = "ServerConfig";
                    options.ConfigureDbContext = builder =>
                        builder.UseSqlServer(_connectionString,
                            sql => sql.MigrationsAssembly(_migrationsAssembly));
                    options.EnableTokenCleanup = true;
                    options.TokenCleanupInterval = 30;
                });
`

**Comment by simonare** [comment]
Thank you very much @smairo. 
your solution is the cleanest and straight to the point. It will definitely work.
