### ISSUE TITLE
Make Scheduled PersistedGrant clean up handle large results

### ISSUE THREAD

**Issue by minhSkoolbo** [IdentityServer/IdentityServer4.EntityFramework#108]
Hi find that this query is called by the identityServer once in a while. i guess it's query the expired grant to remove from the table? 
`
@__UtcNow_0 datetimeoffset(7))SELECT [x].[Key], [x].[Type], [x].[ClientId], [x].[CreationTime], [x].[Data], [x].[Expiration], [x].[SubjectId]  FROM [PersistedGrants] AS [x]  WHERE [x].[Expiration] < @__UtcNow_0
`
Sometimes it timeout and after a few failures, the persistedgrant is too big for later query to complete and thus always timeout.
How do we config the schedule and timeout setting for this? Is there any better practice than regular clean up by the app itself as is?

**Comment by scottbrady91** [comment]
Any method of cleaning up the database is fine. As you say, the current EF stuff can start timing out with larger databases. I would recommend scheduling a SQL script, external to IdentityServer.

**Comment by brockallen** [comment]
I can also look at tailoring that query to do fewer at a time for this scenario.

**Comment by brockallen** [comment]
Also, how many do you have in there that causes it to start failing? 10K? 100K? 1M?

**Comment by minhSkoolbo** [comment]
Thanks for looking into this guys. I have normally less than 100K entries in the PersistedGrant table. However after a few timeout and failure, the number of row may be bloating to much more than that.

Do you know if the default EF query can be configured from anywhere? I tried to search for it in the source code but couldn't find it yet.

**Comment by brockallen** [comment]
I added a `TokenCleanupBatchSize` to `OperationalStoreOptions` to remove a smaller amount at a time. Defauls to 100.

**Comment by brockallen** [comment]
Before I do a formal release, can you test against the myget nightly build of this to ensure it's working for you? Thanks.
