### ISSUE TITLE
How can I create IdentityClaim entities?

### ISSUE THREAD

**Issue by CamiloTerevinto** [IdentityServer/IdentityServer4.EntityFramework#109]
I am creating an Angular Material admin for an internal Identity Server. I'm using this to access `DbSet`s that are not available in the `ConfigurationDbContext`:

    private readonly DbSet<IdentityResource> resources = context.Set<IdentityResource>();
    private readonly DbSet<IdentityClaim> claims = context.Set<IdentityClaim>();

While I can create `IdentityResource`s easily, the same does not hold true for `IdentityClaim`. What's the reasoning behind not providing a public `IdentityResourceId` property in `IdentityClaim`? Are we not supposed to create `IdentityClaim`s based on existing `IdentityResource`s?
It would be easy enough to create `IdentityResource`s with a `List<IdentityClaim>` with them, but this does not allow further creations.

**Comment by CamiloTerevinto** [comment]
The same question holds for `ClientScope`. How can I create a `ClientScope` if it does not have a `ClientId` property?

**Comment by brockallen** [comment]
Why don't you navigate the hierarchy?

**Comment by CamiloTerevinto** [comment]
@brockallen 
If I attempt to insert this:

    Id = -2147482647
    IdentityResource.IdentityResourceId = 1
    Type = "profile"

Then Entity Framework fails with:

    "Cannot insert explicit value for identity column in table 'IdentityResources' when IDENTITY_INSERT is set to OFF."

**Comment by brockallen** [comment]
Sure, that'd a DB-generated value, IIRC

**Comment by CamiloTerevinto** [comment]
@brockallen  Nevermind, I now understood what you meant by navigating.

Solved it with this:

    var identityResource = await context.IdentityResources
        .Include(x => x.UserClaims)
        .Where(x => x.Id == model.IdentityResource.Id)
        .SingleAsync();
    identityResource.UserClaims.Add(model);
