### ISSUE TITLE
TokenCleanup expires valid tokens

### ISSUE THREAD

**Issue by Ollienator** [IdentityServer/IdentityServer4.EntityFramework#113]
I ran into an issue using IdentityServer4 with PostgreSQL as an EF backend.   Since the model uses DateTime instead of DateTimeOffset, the Pgsql layer writes the expiration converted to UTC to the database, but reads it back as DateTimeKind.Unspecified.  This gets treated as the local timezone in comparisons, thus (depending on the machines timezone settings) expiring tokens that should still be valid.

The following fixes the token cleanup for me:

TokenCleanup.cs line 105
```cs
var expired = context.PersistedGrants.Where(x => x.Expiration.AssumeUtc() < DateTimeOffset.UtcNow).ToArray();
```

And DateTime extensions
```cs
public static DateTime? AssumeUtc(this DateTime? value)
{
    return value.HasValue ? AssumeUtc(value.Value) : value;
}

public static DateTime AssumeUtc(this DateTime value)
{
    return value.Kind == DateTimeKind.Unspecified ? DateTime.SpecifyKind(value, DateTimeKind.Utc) : value;
}
```

Regards,
O.

**Comment by brockallen** [comment]
Yea, sorry -- the use of DateTimeOffset in the code was simply a bug. It's fixed now. Thanks.

**Comment by brockallen** [comment]
Before I do a formal release, can you test against the myget nightly build of this to ensure it's working for you? Thanks.
