### ISSUE TITLE
How to customize table names

### ISSUE THREAD

**Issue by leechen** [IdentityServer/IdentityServer4.EntityFramework#114]
Hi, 
I am trying to rename tables/columns/indexes to follow Postgresql convention. Here is the approach I am taking:
1. Add a DbContext class:
```
    public class OAuthConfigDbContext : ConfigurationDbContext
    {
        public OAuthConfigDbContext(DbContextOptions<ConfigurationDbContext> options, ConfigurationStoreOptions storeOptions)
            : base(options, storeOptions)
        {
        }

        protected override void OnModelCreating(ModelBuilder builder)
        {
            base.OnModelCreating(builder);
            DbModelHelper.RenameModel(builder);
        }
    }
```
2. In Startup.ConfigureServices, setup DI
```
             services.AddDbContext<OAuthConfigDbContext>(options => 
             options.UseNpgsql(connectionString));
             ...

            services.AddIdentityServer()
                .AddConfigurationStore(options =>
                {
                    options.ConfigureDbContext = builder =>
                    builder.UseNpgsql(connectionString,
                        db => db.MigrationsAssembly(migrationsAssembly));
                })
```
The migration generated looks good. But when I use it, the IdentityServer still uses default table names: 
Error Message:
 Npgsql.PostgresException : 42P01: relation "IdentityResources" does not exist

Any suggestions?

**Comment by brockallen** [comment]
Did you try setting any of the `TableConfiguration` settings, such as: https://github.com/IdentityServer/IdentityServer4.EntityFramework/blob/dev/src/IdentityServer4.EntityFramework/Options/ConfigurationStoreOptions.cs#L37

**Comment by leechen** [comment]
Good point. Does it support something that is general like this? Or has to be done for each table/column/index.
```
        static internal void RenameModel(ModelBuilder builder)
        {
            foreach (var entity in builder.Model.GetEntityTypes())
            {
                entity.Relational().TableName = StringHelper.ToSnakeCase(entity.Relational().TableName);

                foreach (var prop in entity.GetProperties())
                {
                    prop.Relational().ColumnName = StringHelper.ToSnakeCase(prop.Name);
                }

                foreach (var key in entity.GetKeys())
                {
                    key.Relational().Name = StringHelper.ToSnakeCase(key.Relational().Name);
                }

                foreach (var key in entity.GetForeignKeys())
                {
                    key.Relational().Name = StringHelper.ToSnakeCase(key.Relational().Name);
                }

                foreach (var index in entity.GetIndexes())
                {
                    index.Relational().Name = StringHelper.ToSnakeCase(index.Relational().Name);
                }
            }
        }
```

**Comment by brockallen** [comment]
one by one

**Comment by bion19** [comment]
As far as I can tell this only allows to change the table name.  I made a pull request that allows the custom DbContext that can implement the snake case function in the OnModelCreating override.

https://github.com/IdentityServer/IdentityServer4.EntityFramework/pull/115

**Comment by brockallen** [comment]
Merged.

**Comment by brockallen** [comment]
Before I do a formal release, can you test against the myget nightly build of this to ensure it's working for you? Thanks.

**Comment by bion19** [comment]
Yes, I'll check it tonight or tomorrow and post back.  Thanks!

**Comment by bion19** [comment]
It works for me.  Tested v2.1.0-build00143.

**Comment by brockallen** [comment]
Thanks.

**Comment by Janidbest** [comment]
I see, this now released in the latest NuGet, Probably worth a blog post.
