### ISSUE TITLE
Question about ConfigurationDbContext migrations from 1.0.1 to 2.0.0

### ISSUE THREAD

**Issue by dls314** [IdentityServer/IdentityServer4.EntityFramework#117]
I have an IdentityServer4 instance using IdentityServer4.EntityFramework version 1.0.1 with migrations generated for the ConfigurationDbContext.

I'm in the process of upgrading to IdentityServer4 2.0.2 and IdentityServer4.EntityFramework version 2.0.0 and I'm trying to do it like so...

1. Upgrade nuget packages
2. Add a new migration against the ConfigurationDbContext from the new nuget package version

This works fine for the PersistedGrantDbContext (few or no changes), but for the ConfigurationDbContext I get an error when attempting to apply the migrations:

`Cannot change column 'Id': used in a foreign key constraint 'FK_IdentityClaims_IdentityResources_IdentityResourceId'`

Is there a better method for such an upgrade?

**Comment by dls314** [comment]
I think it's possible that I'm seeing a bug from Pomelo MySQL provider like this: https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/issues/362

**Comment by brockallen** [comment]
All set on this issue -- can we close?

**Comment by masoapps** [comment]
I'm also seeing this issue at the moment, did you find a reasonable workaround @dls314 ?

**Comment by dls314** [comment]
I never worked through caleblloyd's recommendation over in #423 about adding code manually to the migration, but I'm sure it's an answer.

**Comment by masoapps** [comment]
Thanks @dls314 I'll give that a go 👍
