### ISSUE TITLE
Multiply clients

### ISSUE THREAD

**Issue by MrPhelko** [IdentityServer/IdentityServer4.EntityFramework#121]
Hello. 
I`m doing SaaS service here each client having some app.
Can I make it so that the client can only go to his VM?

**Comment by brockallen** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue.

Please use one of the our free or commercial support options

See [here](https://identityserver4.readthedocs.io/en/release/intro/support.html) for more details.

Thanks!
