### ISSUE TITLE
Client/Configuration Cache

### ISSUE THREAD

**Issue by mantasaudickas** [IdentityServer/IdentityServer4.EntityFramework#124]
Hello,

I have UI for client configuration in my app... However it seems that IdentityServer4 has some kind of cache, which is used and changes in client does not work immediately.
During configuration I add this: .AddConfigurationStoreCache()
However I do not see any way to clear it when needed. Do you have any suggestions?

**Comment by brockallen** [comment]
We don't have an API to clear our cache. If you need this, then implement your own (look for the Caching section): http://docs.identityserver.io/en/release/topics/startup.html
