### ISSUE TITLE
Migrations missing columns from 1.0 to 2.0

### ISSUE THREAD

**Issue by AshleyPoole** [IdentityServer/IdentityServer4.EntityFramework#125]
Hi,

Using IdentityServer4 2.0 with Entity Framework on SQL Server, but when generating migrations from 1.0 to 2.0, we're missing columns.

The columns that it's not picking up, are for example some of the one's in this commit. At first we thought it was an issue with the use of RTM, then RC packages, so we deleted those migrations and re-ran a new migration but still getting issues.

https://github.com/IdentityServer/IdentityServer4.EntityFramework/commit/6fb56ebac8bc9598843327451e03ca300ab48364

We're getting the following errors when running the app. Note, we're not using auto updates at run-time.
```
Invalid column name 'BackChannelLogoutSessionRequired'.
Invalid column name 'BackChannelLogoutUri'.
Invalid column name 'ClientClaimsPrefix'.
Invalid column name 'ConsentLifetime'.
Invalid column name 'Description'.
Invalid column name 'FrontChannelLogoutSessionRequired'.
Invalid column name 'FrontChannelLogoutUri'.
Invalid column name 'PairWiseSubjectSalt'.
```

Is there anything we're doing wrong or anything to check? Thanks.

**Comment by AshleyPoole** [comment]
Is sounds very similar to the following issue report, but It's not clear what the resolution was exactly - https://github.com/IdentityServer/IdentityServer4.EntityFramework/issues/112

**Comment by brockallen** [comment]
Sorry, don't know. As you said, it sounds like the migration is somehow missing those columns... not sure why.

**Comment by brockallen** [comment]
All set on this issue -- can we close?

**Comment by AshleyPoole** [comment]
Sadly nothing we tried, even removing RTM and RC migrations and re-migrating from 1.5 to 2.0 helped. We had to remove all migrations which of course isn't a great situation as a upgrade path for people using 1.X in production.

**Comment by brockallen** [comment]
Yea, sorry that Microsoft's EF migrations don't work as well as I think we'd all like. Given that this is pretty much our experience with migrations, we explicitly point out in our docs that you really need to own that schema and think about how you plan changes over time: http://docs.identityserver.io/en/release/reference/ef.html#database-creation-and-schema-changes-across-different-versions-of-identityserver

I know you've already dealt with this and probably come to that conclusion already, but just in case someone else reading this hasn't.

Sounds like you have your workaround, so I'll close.
