### ISSUE TITLE
Update to 1.0.1 ASP.NET Core packages

### ISSUE THREAD

**Issue by scottbrady91** [IdentityServer/IdentityServer4.EntityFramework#13]

**Comment by brockallen** [comment]
which ones require updating?

**Comment by scottbrady91** [comment]
Some ASP.NET ones (see https://blogs.msdn.microsoft.com/webdev/2016/09/13/asp-net-core-sept-2016-patch/) and all of the EF Core packages.

**Comment by scottbrady91** [comment]
Done in ce1fada
