### ISSUE TITLE
How's the operational data integrated with Identity Server

### ISSUE THREAD

**Issue by iberodev** [IdentityServer/IdentityServer4.EntityFramework#14]
I've had a look at the QuickStart tutorial with EF persistance layer but I'd like to confirm a few things about this module.

As I understood it's a persistance module in the way that it can generate the entities and mappings for a code first database migration approach. It seems to also have some repositories to access data.

But the documentation mentions something else

> There are two types of data that we are moving to the database. The first is the configuration data (scopes and clients). The second is operational **data that IdentityServer produces as it’s being used**. 

I saw that the operational data is all about the `PersistedGrants` table, and it looks like this table has something to do with permissions for clients? What's this persisted grants used for? and more important, is there any integration behind the scenes with Identity Server's endpoints in a way that records are inserted "magically"? 

I am asking this because the documentation says that the operational data is being produced as it's being used, but I fail to understand how this happens or what scenarios (flows?) is this related to.

Hopefully my question makes sense!

**Comment by brockallen** [comment]
They represent authorization code, refresh tokens, reference tokens, and user consent.

**Comment by PivotalAnimal** [comment]
Curious, has anything else changed in the models? E.G. Client, Scope, etc. or the interfaces that deal with what you have not mentioned? I am hoping that changes will be minimal. I have yet to explore. Thanks in advance!

**Comment by scottbrady91** [comment]
IIRC all stores and services have changed. The Client and Scope entities have definitely changed, so your mappers may need updating at least.
