### ISSUE TITLE
ClientScope/ScopeSecret should be in the singular form?

### ISSUE THREAD

**Issue by Simply-Awesome** [IdentityServer/IdentityServer4.EntityFramework#15]
namespace IdentityServer4.EntityFramework
{
    public class EfConstants
    {
        public class TableNames
        {
            ...
            public const string ScopeSecrets = "ScopeSecrets"; // should be  "... ScopeSecret = "ScopeSecrets"; 
           ...
            public const string ClientScopes = "ClientScopes"; // should be "... ClientScope = "ClientScopes";
            ...
        }
    }
}

I know this is very minor, but I find myself obsessing over the dots on an "I" or the crosses on a "T"

**Comment by scottbrady91** [comment]
The above code changes the property names (and not the values/the table names themselves), but I'm going to assume you are talking about pluralized table names here.

For the IdentityServer 3 version of this project the table names where pluralized and I've continued with this style to keep things consistent. Whilst I understand some people may prefer table names to be singular, I feel this is a stylistic decision.

If you require singular table names, you can override the existing DbContexts and assign names yourself with code such as:
```
modelBuilder.Entity<Client>(client => {
    client.ToTable(EfConstants.TableNames.Client);
}
```
