### ISSUE TITLE
AutoMapperMappingException for Clients

### ISSUE THREAD

**Issue by mschnecke** [IdentityServer/IdentityServer4.EntityFramework#16]
Hi, 
I played around with the sample "IdentityServer4.Samples\Quickstarts\8_EntityFrameworkStorage". The Startup.cs consists the method "InitializeDatabase" where predefined clients and scopes were added to the DBContext. After that i tried to retrive the clients. The Extension method "ToModel" raises an automapper exception.

[AutoMapperMappingException.pdf](https://github.com/IdentityServer/IdentityServer4.EntityFramework/files/486606/AutoMapperMappingException.pdf)

"IdentityServer4.EntityFramework": "1.0.0-rc1-update2",
"Microsoft.EntityFrameworkCore.Sqlite":  "1.0.0",

Regards,
Micha

**Comment by scottbrady91** [comment]
To be clear, this is using the quickstart part 8 found in the samples repo, which you've changed it to use SQLite?

**Comment by mschnecke** [comment]
Yes, instead of localdb, I use SQLite in Docker scenario

**Comment by scottbrady91** [comment]
Is this no longer an issue?

**Comment by mschnecke** [comment]
Sorry no, it is an issue yet. I created a sample project for you: (https://github.com/mschnecke/QuickstartIdentityServer.git). I cloned the 8_EntityFrameworkStorage solution from IdentityServer4.Samples and changed the Startup.cs with SQLite related stuff. Line 108 is the trouble maker.

**Comment by scottbrady91** [comment]
You've got some bad state in your SQLite DB (see https://github.com/mschnecke/QuickstartIdentityServer/blob/master/src/QuickstartIdentityServer/bin/Debug/netcoreapp1.0/QuickstartIdentityServer.db)

Delete this and rerun the application. This time the initialization will run correctly and you won't have this error.

**Comment by mschnecke** [comment]
yes, this works for the first time, but if you run the application a second time (database already exists), the error occurs again.

**Comment by scottbrady91** [comment]
Okay, so when you go to [iterate through the clients](https://github.com/mschnecke/QuickstartIdentityServer/blob/master/src/QuickstartIdentityServer/Startup.cs#L106), you are not getting any of the required collections (in this immediate case, the AllowedGrantsTypes). Automapper is throwing because the collections are null, something which should never happen, especially not with AllowedGrantTypes.

The reason the collections are null is because Entity Framework Core does not support lazy loading, only explicit loading (e.g. includes).

**Comment by scottbrady91** [comment]
FYI: It's not an issue on the first run as the collections are still in the object graph from when they were added.

**Comment by mschnecke** [comment]
Thanks, this works for now:

var entityClients = context.Clients
					.Include(x => x.AllowedGrantTypes)
					.Include(x => x.AllowedScopes)
					.Include(x => x.RedirectUris)
					.Include(x => x.PostLogoutRedirectUris)
					.ToList();

				foreach (var client in entityClients)
				{
					var domainModel = client.ToModel();
				}
