### ISSUE TITLE
Enabled on Client is not respected

### ISSUE THREAD

**Issue by benhysell** [IdentityServer/IdentityServer4.EntityFramework#17]
https://github.com/IdentityServer/IdentityServer4.EntityFramework/blob/dev/src/IdentityServer4.EntityFramework/Stores/ClientStore.cs#L26

Doesn't match InMemory

https://github.com/IdentityServer/IdentityServer4/blob/ccb9cfc407aea220f7d654bec100a1bde41a640b/src/IdentityServer4/Stores/InMemory/InMemoryClientStore.cs#L35

InMemory only returns Clients that are Enabled, where EF will return all clients if they match, enabled or not.

**Comment by scottbrady91** [comment]
Okay, thanks for flagging that.

I'll look into this.

**Comment by scottbrady91** [comment]
I've opened this up for discussion in the core repo: https://github.com/IdentityServer/IdentityServer4/issues/353

**Comment by scottbrady91** [comment]
All consuming implementations have been updated to check for null and disabled being returned from the Client and Scope stores. Seems the `InMemoryClientStore` was the odd one out.
