### ISSUE TITLE
Provide an option to set default schema for ConfigurationDbContext and PersistedGrantDbContext

### ISSUE THREAD

**Issue by etrafiee** [IdentityServer/IdentityServer4.EntityFramework#18]
Hi,
Thanks for your work, If you could provide an option to set default schema for ConfigurationDbContext and PersistedGrantDbContext while adding those stores to IdentityServer host that would be great.

**Comment by WillTartak** [comment]
I cannot figure out how to use this. I've set the schema in the Migrations and EF created the tables in the proper schema. 

How do I configure the ConfigurationDbContext to use that schema? 

I keep getting an error in Startup when I try to populate Clients from the In Memory ones used during QuickStart. The error shows that the schema is not being used when querying for Clients:

An Exception occurred in the database while iterating the results of a query. Invalid object name 'Clients'.

The generated SQL is:
SELECT CASE
            WHEN EXISTS (
                       SELECT 1
                       FROM [Clients] as [c])
            THEN CAST(1 AS BIT) ELSE CAST(0 AS BIT)
END

My schema is not being used to query the table.

**Comment by scottbrady91** [comment]
Have you set [ConfigurationStoreOptions](https://github.com/IdentityServer/IdentityServer4.EntityFramework/blob/dev/src/IdentityServer4.EntityFramework/Options/ConfigurationStoreOptions.cs)? These were released with RC2.

 EF cannot use a custom schema without first being made aware of it.

**Comment by WillTartak** [comment]
Thanks for the quick response.

I'm away from the code but have something like this in ConfigureServices

services.Configure<ConfigurationStoreOptions>(options => DefaultSchema("idsrv");

I guess that is what I can't figure out. Should I just create a subclass?

**Comment by WillTartak** [comment]
Oops, I see the editor changed what I wrote. Now that I have the code in front of me, this is what I have in ConfigureServices:

`services.Configure<ConfigurationStoreOptions>(options =>
{
	options.DefaultSchema = "idsrv";

});`

**Comment by scottbrady91** [comment]
Why are you registering the options manually and not using something like:

```
services.AddIdentityServer().AddConfigurationStore(builder =>
    builder.UseSqlServer(connectionString,
         options => options.MigrationsAssembly(migrationsAssembly)),
    storeOption => storeOption.DefaultSchema = "idsrv");
```

**Comment by WillTartak** [comment]
Hi Scott,

Thank you!
I figured there was something I was doing wrong. 

For my own enlightenment, where in the source code would I have found that assignment? I started to look for something like that but was not sure where it would be.

Again, thank you!

**Comment by scottbrady91** [comment]
https://github.com/IdentityServer/IdentityServer4.EntityFramework/blob/release/src/IdentityServer4.EntityFramework/Extensions/IdentityServerEntityFrameworkBuilderExtensions.cs#L19
