### ISSUE TITLE
Invalid_grant after updating to update2

### ISSUE THREAD

**Issue by Eneuman** [IdentityServer/IdentityServer4.EntityFramework#20]
Hi!
I just updated to the latest rc-package and now when I do this:

```
var refreshToken = await _contextAccessor.HttpContext.Authentication.GetTokenAsync("refresh_token");
var response = await tokenClient.RequestRefreshTokenAsync(refreshToken);
```

i received this:
```
Json = {{
  "error": "invalid_grant"
}}
```
as response.json.

It seems like the first call to RequestRefreshTokenAsync works, but the **second call to it fails**.

This was working fine before upgrading.
Are there any breaking changes in Update2 ?

**Comment by brockallen** [comment]
Is the refresh token mode single-use, or re-use?

**Comment by Eneuman** [comment]
Single Use ofc :( 
I should have checked that first. 
Thanks for your quick answer !
