### ISSUE TITLE
How do I use custom ConfigurationDbContext and PersistedGrantDbContext? 

### ISSUE THREAD

**Issue by pkapare** [IdentityServer/IdentityServer4.EntityFramework#21]
I renamed some of configuration table (Clients, Scopes etc.) and also put it in new database schema called "Security". I created custom ConfigurationDbContext by overriding OnModelCreating method where I mapped IdentityServer4.EntityFramework.Entities to new tables and schema. e.g.
            modelBuilder.Entity<Scope>( b =>
            {
                b.ToTable("Scopes", "Security");
            });
Now when I run IdentityServer I am getting error.  
An exception of type 'System.Data.SqlClient.SqlException' occurred in Microsoft.EntityFrameworkCore.dll but was not handled in user code

Additional information: Invalid object name 'Scopes'.
I believe it is using default ConfigurationDbContext  and not one I defined which has schema details.
Any idea how do I do that?

**Comment by brockallen** [comment]
We're working on an approach to make changing table names/schemas easier. Stay tuned!

**Comment by aggieben** [comment]
Any progress on this?  I was also hoping to customize the `ConfigurationDbContext`.

**Comment by brockallen** [comment]
> I was also hoping to customize the ConfigurationDbContext.

What specifically?

**Comment by aggieben** [comment]
Well, in my case I wanted to add some properties to the models (i.e., `Client.Tenant`).  I eventually realized that it's just a limitation of EF that prevents it - or at least it's very non-obvious.

**Comment by brockallen** [comment]
We've not designed for our configuration models to be extended, so yea... this seems difficult.

**Comment by Baklap4** [comment]
Any plans on designing this feature? I'm looking for a way to extend the `Client` model

**Comment by brockallen** [comment]
Feel free to fork this repo.
