### ISSUE TITLE
Would it be possible to change the Id type of a Client to be Guid instaed of an int?

### ISSUE THREAD

**Issue by Simply-Awesome** [IdentityServer/IdentityServer4.EntityFramework#22]
Ideally, it would be best if the Id type could be generically stated. For example, one may decide to use a "String" or a "Long" instead of a "Guid" as the Id type.

While we are at it, we might as well do the same for Scopes.

**Comment by brockallen** [comment]
The ClientName is the unique identifier for a client. This is where you should put the guid (in your admin provisioning tool). The ID is just the PK. 

Also, EF6 has limitations with generic classes as entities. Do you know if EF Core has same problem?

**Comment by Simply-Awesome** [comment]
EF Core does have some of the same issues - e.g. like when it comes to the use of the RoleManager.

My first impression was to find the Client by the Id (and not the ClientId that should also be unique); following the lead from AspNetIdentity that uses strings as PK for Users.

What you are saying is find the Client by the ClientId (like you would find a User by the username instead of the UserId) and leave the PK alone. I see.

**Comment by brockallen** [comment]
All of our stores only ever find the client by ClientId.

**Comment by brockallen** [comment]
So is this still a worthwhile feature request? // @scottbrady91

**Comment by scottbrady91** [comment]
Do any relational database providers have restrictions on what data type the primary key can be? I suppose it may be useful in that case. But then again, are there any relational databases that don't allow int primary keys?

@Simply-Awesome We currently are using int's as our primary key type. For GUIDs are you thinking of ASP.NET Identity?

**Comment by Simply-Awesome** [comment]
@scottbrady91 
I doubt there are any that don't allow int as PK. String should be universally compatible too; Guid less so.
Yes, I was initially thinking AspNetIdentity that I know has issues with the RoleManager; I need this to flawlessly work with ID4.

I was thinking that it would be better to have the Id (not referring to ClientId here) as a String/Guid instead of int mostly because I would prefer to not have it guessable if searches were made by the Id. 

At the moment I am thinking, that as long as I can use the ClientId as a unique identifier, I can ignore the Id completely.

Unless you really think its a good idea to allow generic implementations, we can ignore this feature request for now.

**Comment by brockallen** [comment]
Ok, I'll close. I'm not interested in increasing the complexity of what we have to support.

**Comment by xperiandri** [comment]
It is must have. Generic primary key is required feature.
What would I do if I use GUID as primary key in APN.NET Identity? Some entities will have GUIDs as primary keys and some ints. Looks like a zoo.
The main reason of using GUIDs as keys is a uniform distribution of values.

**Comment by brockallen** [comment]
>  The main reason of using GUIDs as keys is a uniform distribution of values.

I used to prefer GUIDs, but I've been through this battle over & over with DBAs and as far as I'm concerned I lost. DBAs (at least the several ones I dealt with) refuse to use GUIDs as PKs because non-sequential and clustering. They tell me that I can have a non-sequential GUID as a unique ID for application-level access, but I'm always told that they require a int for the physical PK (for sequence and clustering reasons).

Adding the PK as a generic in this library adds overhead for us in terms of maintenance (and we're not being paid to maintain this library). I'd like to have a really strong argument to convince me.
