### ISSUE TITLE
Refactor the TokenCleanup

### ISSUE THREAD

**Issue by xyting** [IdentityServer/IdentityServer4.EntityFramework#23]
@brockallen @leastprivilege 

The current TokenCleanup implementation is enigmatical, in my view, it SHOULD use `IApplicationLifetime` interface under the `Microsoft.AspNetCore.Hosting` namespace. The interface is designed to give a developer the opportunity to gracefully startup but mostly shutdown the application. It is comprised of three properties and one method respectively: `ApplicationStarted`, `ApplicationStopping`, `ApplicationStopped`, and `StopApplication()`.

IOW, the TokenCleanup's impls SHOULD register the Start method to `ApplicationStarted` and register the Stop to `ApplicationStopped` or `ApplicationStopping`. and the DbContext should get from DI.

Maybe I SHOULD make a PR to this repo?

**Comment by brockallen** [comment]
great idea! PR welcome

**Comment by xyting** [comment]
yelp, I will make PR this weekend.

**Comment by xyting** [comment]
@brockallen  see  #24

**Comment by brockallen** [comment]
Thanks. I'll get to it when I can (my ability to work on IdSvr4 goes in cycles).

**Comment by MienDev** [comment]
@xyting  good idea and good job.

I viewed of part of your code some minutes ago. In my humble opinion, but it can be better for th extension method. 
In convention, an Use... method is more welcome in `Configure` section,  some thing like  `app.UseIdentityServerTokenCleaner()`. 


The pesudo code following for your reference:

```c#
// in startup.cs > Configure()
app.UseIdentityServerTokenCleaner();

// for the extension class
public static class SomeExtentsionClassName{
  public IApplicationBuilder UseIdentityServerTokenCleaner(this IApplicationBuilder app){
  
    // resolve 
    var appLife = app.ApplicationServices.GetService<IApplicationLifetime>();
    var tokenCleaner = app.ApplicationServices.GetService<TokenCleanup>();
    
    // control
    if(tokenCleanup != null) {
      	appLifetime.ApplicationStarted.Register(tokenCleanup.Start);
      	appLifetime.ApplicationStopping.Register(tokenCleanup.Stop);
    }
	// return for chain invoking.
    return app;
  }
}
```

bla, bla...

**Comment by xyting** [comment]
@MienDev 
Thanks your review.

Yes, that is my first version I done, but I think again, the token cleanup only relative with `OperationalDbContext` or `IPersistedGrantStore`, that's to say, if the end users do not DI this `IPersistedGrantStore`,  that extension method is funny （throw exception if tokenCleaner == null will more meaningful).

On the other hand, however, the all TokenCleanup depended services had been injected when DI `IPersistedGrantStore`,  and this put all code together.

**Comment by scottbrady91** [comment]
I've submitted some initial updates to your PR, let me know what you think.

**Comment by xyting** [comment]
@scottbrady91 

Check null maybe more meaningful, because maybe the end users have not DI `IPersistedGrantStore` or they only use `AddConfigurationStore` to store the configuration and have alternative `IPersistedGrantStore`, such as redis.

```csharp
var tokenCleanup = app.ApplicationServices.GetService<TokenCleanup>();
if (tokenCleanup == null )
{
      throw new Exception("The AddOperationalStore must be call first");
}
```

**Comment by scottbrady91** [comment]
Good point, there are similar approaches in the core library checking for required registrations. I'll add this in shortly.

I've called it `UseIdentityServerEfTokenCleanup` to try and make it clear that this is for the EF side of things only. It shouldn't matter what EF database provider they are using.

If they aren't using EF they won't be using this package and would therefore need to implement their own TokenCleanup.

**Comment by xyting** [comment]
yelp, the name `UseIdentityServerEfTokenCleanup` means what  it done.

**Comment by brockallen** [comment]
done, thanks
