### ISSUE TITLE
To Many Properties on Client

### ISSUE THREAD

**Issue by DerAlbertCom** [IdentityServer/IdentityServer4.EntityFramework#26]
The Entity of Client has the Propierties  **PublicClient** and **AllowPromptNone**, for these they are no properties on https://github.com/IdentityServer/IdentityServer4/blob/dev/src/IdentityServer4/Models/Client.cs

**Comment by scottbrady91** [comment]
Well spotted. Both the old properties and their updated versions are in there. Don't know how I managed that...

**Comment by scottbrady91** [comment]
Done on dev. Will look into releasing this as an update.
