### ISSUE TITLE
X509 Secret: String or binary data would be truncated

### ISSUE THREAD

**Issue by scottbrady91** [IdentityServer/IdentityServer4.EntityFramework#29]
Value for secret type X509CertificateBase64 found in IdentityServer4.EntityFramework.Host is throwing `System.Data.SqlClient.SqlException` with message 'String or binary data would be truncated' upon EF save changes.

**Comment by leastprivilege** [comment]
that's potentially quite a long string >2k

**Comment by dls314** [comment]
Just saw this while trying to push [this client](https://github.com/IdentityServer/IdentityServer4/blob/5d0892eaec6c29cf23e12801c8a5596d7c0c393b/src/Host/Configuration/Clients.cs#L35-L49) to an EF store.

**Comment by brockallen** [comment]
Secret value length was changed to 2k.
