### ISSUE TITLE
Concurrency exceptions authorisation code flow leads to invalid grant 

### ISSUE THREAD

**Issue by miiitch** [IdentityServer/IdentityServer4.EntityFramework#30]
i'm developping a Xamarin app, and I use the Xamara.Auth component. I've no pb with the in memory operationnal store during login. But when I switched to the sql azure, I have lot of issues because of concurrency exception during the authentication flow. In this file I have all the debug log from the validation of the login form to the message on the mobile app that says "invalid grant". (Sorry the logs are duplicated)

[logfail.txt](https://github.com/IdentityServer/IdentityServer4.EntityFramework/files/548139/logfail.txt)

**Comment by brockallen** [comment]
Are there 2 HTTP requests that try to remove the same record? Is that why the log has duplicate entries?

**Comment by brockallen** [comment]
Any update?

**Comment by brockallen** [comment]
we'll call this a dup of #9
