### ISSUE TITLE
No client with id found . aborting

### ISSUE THREAD

**Issue by nburak** [IdentityServer/IdentityServer4.EntityFramework#31]
Hello, I am trying to get clients from database and i started to use Identity Server 4. Entity Framework Project.
in spite of me to have a client which has an id as 'resClient'  in database, I am getting this error. 
What may cause this problem?
Thanks for your help...
![bigerror](https://cloud.githubusercontent.com/assets/7663595/19676738/92a81304-9a9e-11e6-93b8-b2284a840f0f.PNG)

**Comment by xyting** [comment]
View your db to confirm have the Client in database or not, if haven't, INSERT it into database. I had use this package in my production, haven't the same issues.

**Comment by nburak** [comment]
This is my client table in database.  
![bigerror2](https://cloud.githubusercontent.com/assets/7663595/19677801/af4f5418-9aa3-11e6-89de-310261deb169.PNG)

**Comment by nburak** [comment]
I found a solution 
Source of the problem is column 'Enabled' in Client table to have a value as false. I set it to true and it works fine. 

On the other hand, Now Identity server validates my client but while it is trying to create an Access token, i get this error.

crit: IdentityServer4.Hosting.IdentityServerMiddleware[0]
      Unhandled exception: System.ArgumentException: IDX10401: Expires: '10/25/2016 09:12:47' must be after NotBefore: '10/25/2016 09:12:47'.

**Comment by scottbrady91** [comment]
Glad to hear you figured it out. The enabled check is performed in the Core (IdentityServer4) repository. After all, a client application that has been disabled should not be allowed to authenticate.

For the second issue, please open a new issue in the core repository.
