### ISSUE TITLE
Changes in model Client entity

### ISSUE THREAD

**Issue by ajtowf** [IdentityServer/IdentityServer4.EntityFramework#33]
Noticed the following changes:

dropped: AllowPromptNone 
renamed: PublicClient -> AllowPlainTextPkce

and a new column: ProtocolType

What should we set this value to when migrating? Can it be null? Ran the following code to see the default value when creating a new client:

    var rc3client = new Client { ClientId = "rc3", ClientName = "rc3"};
    db.Clients.Add(rc3client.ToEntity());
     await db.SaveChangesAsync();

which resultet in ProtocolType -> oidc

**Comment by ajtowf** [comment]
Just confirmed, got unauthorized_client if protocol type isn't set.
Good to know if somebody else already is using this in production :-)

**Comment by totht91** [comment]
It's in RC nobody recommends to use IdentityServer4 in production, due to breaking changes.

**Comment by ajtowf** [comment]
My intention of the issue was to ask a question and highlight this change in case somebody else is migrating their schema. Your comment brings absolutely nothing to the table mate.

**Comment by scottbrady91** [comment]
Thanks for flagging this. As @totht91 said we're currently in RC with breaking changes scheduled before release. I imagine once the project is released future breaking changes will be accompanied by a migration plan as they were in IdentityServer 3.

**Comment by Jenan** [comment]
@ajtowf Thanks for reported these changes, helped me.
