### ISSUE TITLE
PostgresException: 22001: value too long for type character varying(250)

### ISSUE THREAD

**Issue by MienDev** [IdentityServer/IdentityServer4.EntityFramework#34]
with the recent update, the PKCE can be stored in DB as plain text in clientSecrets.value . 
when go with postgresql, exception following thrown,

>  PostgresException: 22001: value too long for type character varying(250)

---- fix (for some one else encounter the same)---
This was solved by add collomn valuetype `[Column(TypeName = "varchar")]`

**Comment by brockallen** [comment]
We changed the secret length to be 2K.
