### ISSUE TITLE
External Providers And AspNet Identity

### ISSUE THREAD

**Issue by jeffchaney1** [IdentityServer/IdentityServer4.EntityFramework#35]
I was working through the Quick Start example for IdentityServer4  (Thank you!), and, I got to  6_aspnet_identity, and, got it working just fine.   I then tried to add the External Provider examples, Google and demo.identityserver.io, to the new IdentityServerWithAspNetIdentity project.  When I try to use either External Provider the call to _signInManager.GetExternalLoginInfoAsync() in AccountController.ExternalLoginCallback() always returns null.

I copied the code from the original IdentityServer project's AccountController.ExternalLoginCallback() to read the info and it is able to pull the information and it is working to get the login information from Google.

I've walked through the instructions on setting up the external providers from the QuickStart as well as from step 4 instructions.  I've tried changing the order of when things are registered in Startup.Configuration(), but, I just am not getting anywhere with this.

I know it's probably something I'm just not understanding, and, I am hoping someone can help me out.

The attached ZIP contains my Startup.cs, Config.cs, Program.cs, AccountController.cs and project.json.

It also contains a Word Document that I pasted screen shots from Firebug with the request/response headers from the google signon and ExternalCallback calls for both the original setup working with the InMemory IdentityServer Quick Start and the ASPNetIdentity version that is not working.

[IdenityServerWithAspNetIdentity Setup.zip](https://github.com/IdentityServer/IdentityServer4.EntityFramework/files/597948/IdenityServerWithAspNetIdentity.Setup.zip)

Thanks for any help or advice you can give and I'm sorry If I posted this in the wrong place.

Jeff Chaney

**Comment by scottbrady91** [comment]
I think you've created this issue in the wrong repository. Sounds like you want [IdentityServer4.AspNetIdentity](https://github.com/IdentityServer/IdentityServer4.AspNetIdentity) or the core repo.

**Comment by jeffchaney1** [comment]
Yea that's where I meant to create it.  Sorry.

**Comment by scottbrady91** [comment]
Reopened in https://github.com/IdentityServer/IdentityServer4.AspNetIdentity/issues/18
