### ISSUE TITLE
MySQL and PostgreSQL Database Provider Integration Tests

### ISSUE THREAD

**Issue by scottbrady91** [IdentityServer/IdentityServer4.EntityFramework#37]
AppVeyor offers MySQL and PostgreSQL for testing. Integration tests should target these when in this environment.

**Comment by scottbrady91** [comment]
See: https://www.appveyor.com/docs/services-databases/

**Comment by brockallen** [comment]
Should we leave this issue open or not?

**Comment by scottbrady91** [comment]
Wow, this has been pending for a while...

I'd like to get this done still. Can I schedule for Jan 18?

**Comment by brockallen** [comment]
Sure, we'll leave it open./

**Comment by brockallen** [comment]
Moved: https://github.com/IdentityServer/IdentityServer4/issues/1865
