### ISSUE TITLE
MissingMethodException on EntityFramework 1.1

### ISSUE THREAD

**Issue by aligin** [IdentityServer/IdentityServer4.EntityFramework#38]
Hello. I'm trying to migrate from 2020IP/TwentyTwenty.IdentityServer4.EntityFrameworkCore to this package. So when I'm using "Microsoft.EntityFrameworkCore": "1.1.0" there is an Exception at /.well-known/openid-configuration.

    MissingMethodException: Method not found: 
    'Microsoft.EntityFrameworkCore.Query.IIncludableQueryable`2<!!0,!!2> 
    Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ThenInclude(Microsoft.EntityFrameworkCore.Query.IIncludableQueryable`2<!!0,System.Collections.Generic.ICollection`1<!!1>>, 
    System.Linq.Expressions.Expression`1<System.Func`2<!!1,!!2>>)'.

Debuging shows it's because of

    public class ResourceStore : IResourceStore
    {
    ..........
        public Task<Resources> GetAllResources()
        {
            var identity = _context.IdentityResources
              .Include(x => x.UserClaims);

            var apis = _context.ApiResources
                .Include(x => x.Secrets)
                .Include(x => x.Scopes)
                    .ThenInclude(x => x.UserClaims) // This include
                .Include(x => x.UserClaims);
         ....
         }
    }
Reproduce is simple: 8_EntityFrameworkStorage. Change project.json to
    
    "Microsoft.NETCore.App": {
      "version": "1.1.0",
      "type": "platform"
    },
and libraries to 1.1.0.

**Comment by satlom** [comment]
+1

**Comment by fberlin** [comment]
+1

**Comment by scottbrady91** [comment]
IdentityServer 4 does not currently support .NET Core 1.1 due to introduced bugs/breaking changes in the security libraries. See https://twitter.com/leastprivilege/status/801723059149357056 for full discussion.

By the way, your colleagues should use the '[Add your reaction](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)' to better show their support.

**Comment by aligin** [comment]
@scottbrady91 Thanks for response. So I'll downgrade to 1.0.1. By the way, we used in production IdSrv since beta2 and it is very stable ).

**Comment by ajtowf** [comment]
Tmp fix for this is to provide your own impl. of IResourceStore, copied the one from this repo and just changed all ThenInclude to Include.
