### ISSUE TITLE
Finding Api resource by scope name returns all resources

### ISSUE THREAD

**Issue by angeor2** [IdentityServer/IdentityServer4.EntityFramework#39]
FindApiResourcesByScopeAsync(IEnumerable<string> scopeNames)
returns all api resources.
from ResourceStore :
` var names = scopeNames.ToArray();
  var query =
                from api in _context.ApiResources
                let scopes = api.Scopes.SelectMany(x => x.Name)
                where names.Intersect(scopeNames).Any()
                select api;`
scopes is never checked and should be something like `api.Scopes.Select(x=>x.Name)`

**Comment by scottbrady91** [comment]
Thanks, well spotted. Will get this resolved asap.

**Comment by brockallen** [comment]
I'm doing an update today, so I'll get to it.

**Comment by brockallen** [comment]
fixed on dev, thanks for reporting and thx for the tests scott.

**Comment by brockallen** [comment]
turns out this exposed an issue in core: https://github.com/IdentityServer/IdentityServer4/issues/527
