### ISSUE TITLE
entity ctors should use same defaults as models

### ISSUE THREAD

**Issue by brockallen** [IdentityServer/IdentityServer4.EntityFramework#4]
e.g. Secret's Type should be SharedSecret.

**Comment by scottbrady91** [comment]
Wouldn't this mean maintaining the defaults across both packages?

**Comment by brockallen** [comment]
I'm working on a solution :)


-Brock
On 9/8/2016 12:00:49 PM, Scott Brady <notifications@github.com> wrote:
Wouldn't this mean maintaining the defaults across both packages?

**Comment by brockallen** [comment]
thoughts? https://github.com/IdentityServer/IdentityServer3.EntityFramework/commit/61ed0b4f48a7b6d197b11e4043a421b64a01d803

**Comment by scottbrady91** [comment]
Looks good! Do we need the if type = type checks though?

**Comment by brockallen** [comment]
Yea, because without them when the derived EF proxy is being created automapper overwrites the collections which is bad. If we could find out how to get automapper to only map the primitives then we'd be in better shape.

**Comment by scottbrady91** [comment]
Gotcha. That's what I get for only running the unit tests.

**Comment by brockallen** [comment]
I don't know if EF Core does the same proxy/derivation trick. Needs some more investigation.

**Comment by brockallen** [comment]
for now i'm going to hard code the default values (until someone else has more time to do something more clever). #lazy

**Comment by brockallen** [comment]
maybe just unit tests to check this would be sufficient

**Comment by brockallen** [comment]
I think I've given up on this in favor of just manually ensuring they have the same values. I know, it's lame, but I don't have time to be clever (famous last words).
