### ISSUE TITLE
Duplicate key on ApiScope name

### ISSUE THREAD

**Issue by taslak** [IdentityServer/IdentityServer4.EntityFramework#41]
I am using identityserver4 and IdentityServer4.Entityframework and want to configure the ApiResource model. 

The following Configuration worked when running in memory.

 public static IEnumerable<ApiResource> GetApiResources()
        {
            var myList = new List<ApiResource>();
 
            var apiResource1 = new ApiResource
            {
                Name = "Group1",
                Enabled = true,
 
                // secret for introspection endpoint
                ApiSecrets =
                {
                    new Secret("noSecret".Sha256())
                },
 
                UserClaims = new List<string> { JwtClaimTypes.ReferenceTokenId },
 
                // API has multiple scopes
                Scopes =
                {
                    new Scope
                    {
                        Name = "internal",
                        DisplayName = "internalGroup"
                    },
                    new Scope
                    {
                        Name = "customer",
                        DisplayName = "external group"
                    },
                 }
            };
 
            var apiResource2 = new ApiResource
            {
                Name = "Group2",
                Enabled = true,
 
                // secret for introspection endpoint
                ApiSecrets =
                {
                    new Secret("noSecret".Sha256())
                },
 
                UserClaims = new List<string> { JwtClaimTypes.ReferenceTokenId },
 
                // API has multiple scopes
                Scopes =
                {
                    new Scope
                    {
                        Name = "internal",
                        DisplayName = "internalGroup"
                    }
                }
            };
            myList.Add(apiResource1);
            myList.Add(apiResource2);
 
            return myList;
        }
 
But when running database migrations, I get a duplicate key 
 
at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)
Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while updating the entries. See the inner exception f
or details. ---> System.Data.SqlClient.SqlException: Cannot insert duplicate key row in object 'dbo.ApiScopes' with uniq
ue index 'IX_ApiScopes_Name'. The duplicate key value is (internal).
 
Should it be possible to have same scope name on different ApiResources?

**Comment by leastprivilege** [comment]
Scope names must be unique.

I'd suggest prefixing them with the api name e.g. "group1.internal"
