### ISSUE TITLE
ConfigurationDbContext missing ApiScopes

### ISSUE THREAD

**Issue by muena** [IdentityServer/IdentityServer4.EntityFramework#45]
Hi,

I'm about to implement a WebAPI for managing IdentityServer4.
I just failed to manage the ApiScopes because they have no DbSet in the ConfigurationDbContext. Should i create a pull request or do you have doubts?

My first attempt to manage IdentityServer was to use the stores (which would be much cleaner imo), but the IClientStore is missing a "FindAll" method. Then I started using the context.
While writing this I found out that if I start contributing to this project, I could also add this missing method to the ClientStore...

What do you think?

Kind regards,
Raphael

**Comment by brockallen** [comment]
> I just failed to manage the ApiScopes because they have no DbSet in the ConfigurationDbContext.

What does this mean? Also, `ApiScope` is a collection on `ApiResource`, which is available on the `ConfigurationDbContext`.

> My first attempt to manage IdentityServer was to use the stores (which would be much cleaner imo), but the IClientStore is missing a "FindAll" method.

The IdentityServer store APIs are not meant to manage the data. They simply model what access IdentityServer needs to the data.
