### ISSUE TITLE
Move Migrations Table Schema

### ISSUE THREAD

**Issue by mitchellmaler** [IdentityServer/IdentityServer4.EntityFramework#46]
Hello, 

I have an Identity Server 4 sharing a database with my API and I am trying to separate the two in the database by schema. I have been successful in moving the API default schema using fluent api and the migrations metadata table using the OnConfiguring method in the DbContext. When I started moving the Idsvr I was able to move the config and ops stores using the options but I am unable to move the migrations table. Is there an option I am missing or can you lend me some help on completing this.

Thanks,
Mitchell Maler

**Comment by brockallen** [comment]
In EF6 I never found a way to do this. Perhaps you can do some research and find out. If you find a way, let us know and we can add it here.

**Comment by mitchellmaler** [comment]
In my API solution I was able to move the migrations table by calling the OnConfiguring() method in my DbContext. 

`protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
{
    var relationalOptions = RelationalOptionsExtension.Extract(optionsBuilder.Options);

    // Specify EF Meta-data History Table Schema
    relationalOptions.MigrationsHistoryTableSchema = "api";

    // Specify EF Meta-data History Table name
    relationalOptions.MigrationsHistoryTableName = "__Migrations";
}`

**Comment by fabiano** [comment]
@mitchellmaler I changed the table schema using the code:

.AddConfigurationStore(
    builder => builder.UseSqlServer(
        connectionString,
        options => options
            .MigrationsAssembly(assembly)
            .MigrationsHistoryTable(HistoryRepository.DefaultTableName, "IdentityServer")),
    options => options.DefaultSchema = "IdentityServer")

.AddOperationalStore(
    builder => builder.UseSqlServer(
        connectionString,
        options => options
            .MigrationsAssembly(assembly)
            .MigrationsHistoryTable(HistoryRepository.DefaultTableName, "IdentityServer")),
    options => options.DefaultSchema = "IdentityServer")

**Comment by brockallen** [comment]
Ok, sorry -- are we all set on this, or do you think we still need changes/modifications in the EF project?

**Comment by brockallen** [comment]
Ah, yes -- I see @fabiano has found the way we set that up. I think you should be all set now @mitchellmaler. Reopen if you're not.

**Comment by brockallen** [comment]
Also, there's this:

```
.AddConfigurationStore(builder =>
                    builder.UseSqlServer(connectionString,
                        options => {
                            options.MigrationsAssembly(migrationsAssembly);
                            options.MigrationsHistoryTable("__EFMigrationsHistory", "foo");
                        }),
                        options => options.DefaultSchema = "foo")

                .AddOperationalStore(builder =>
                    builder.UseSqlServer(connectionString,
                        options =>
                        {
                            options.MigrationsAssembly(migrationsAssembly);
                            options.MigrationsHistoryTable("__EFMigrationsHistory", "bar");
                        }),
                        options => options.DefaultSchema = "bar")
```

**Comment by mitchellmaler** [comment]
Awesome thanks @fabiano @brockallen! I have been busy the last week but will be giving this a try after the holidays.
