### ISSUE TITLE
Maintaining clients and resources

### ISSUE THREAD

**Issue by fabiano** [IdentityServer/IdentityServer4.EntityFramework#47]
Hi,

How do you guys are maintaining the database? I know you don't have a UI project right now so how do you guys do?

I thinking about alternatives right now and new ideas would help a lot.

**Comment by brockallen** [comment]
You would either need to build it yourself, or purchase this product: https://www.identityserver.com/upcoming-products

**Comment by mmillican** [comment]
@brockallen Do you have a more accurate ETA on the admin UI or an approximate cost?

**Comment by brockallen** [comment]
@mmillican You'd have to ask RSK.

**Comment by scottbrady91** [comment]
@mmillican send us a note through the identityserver.com contact form and we'll sign you up to the beta program.

**Comment by mmillican** [comment]
@scottbrady91 Thanks - just sent you a note.
