### ISSUE TITLE
Exception while requesting token from IdentityServer

### ISSUE THREAD

**Issue by waqaskhan540** [IdentityServer/IdentityServer4.EntityFramework#48]
I am using IdentityServer as my authentication server, I have connected it to a mysql database using 'Sapient.Guardian.Mysql' package,

I have got clients, users and scopes in the datatbase and everything was working fine , I was able to generate tokens etc. 

But now when I request a token I get the following exception, 

>InvalidCastException: Unable to cast object of type 'System.String' to type 'System.DateTimeOffset'.
>GetFieldValue

While the Logs show the following 

>Microsoft.EntityFrameworkCore.Query.RelationalQueryCompilationContextFactory:Error: An exception occurred in the database while iterating the results of a query.
System.InvalidCastException: Unable to cast object of type 'System.String' to type 'System.DateTimeOffset'.

**Comment by brockallen** [comment]
I don't think we use DateTimeOffset anywhere in IdentityServer4. You will have to do some more debugging to let us know what the issue is.

**Comment by waqaskhan540** [comment]
Yeah I see that... Its within Microsoft.EntityFramework

**Comment by brockallen** [comment]
Maybe try to repo it without IdentityServer -- it might be an EF issue.

**Comment by waqaskhan540** [comment]
thanks brock... It is an issue with AspNet Identity..

**Comment by brockallen** [comment]
I'd suggest opening an issue w/ Microsoft on it then.
