### ISSUE TITLE
Reduce Indexes on PersistedGrant Entity

### ISSUE THREAD

**Issue by kspearrin** [IdentityServer/IdentityServer4.EntityFramework#50]
Using your EF implementations here as an example, I am doing a bit of research on implementing persisted grant storage for my application (without EF).

Maybe I am misunderstanding how EF works since I don't have a lot of experience with it directly, but it seems you have specified 3 indexes on your `PersistedGrant` table [here](https://github.com/IdentityServer/IdentityServer4.EntityFramework/blob/dev/src/IdentityServer4.EntityFramework/Extensions/ModelBuilderExtensions.cs#L117):

```
grant.HasIndex(x => x.SubjectId);
grant.HasIndex(x => new { x.SubjectId, x.ClientId });
grant.HasIndex(x => new { x.SubjectId, x.ClientId, x.Type });
```

If you were to analyze your queries for "get by SubjectId" and "get by SubjectId AND ClientId" you would see that they are already covered by a single index on SubjectId, ClientId, and Type.

Point being, you should only need 1 index:

```
grant.HasIndex(x => new { x.SubjectId, x.ClientId, x.Type });
```

To cover all query situations that I see in [PersistedGrantStore](https://github.com/IdentityServer/IdentityServer4.EntityFramework/blob/dev/src/IdentityServer4.EntityFramework/Stores/PersistedGrantStore.cs).

**Comment by brockallen** [comment]
I had to check with @IkeEllis, and he was kind enough to provide me with guidance that corroborated @kspearrin. 

> Yes, he's right....as long as the leading edge column is the same.  The leading edge column needs a high distribution of data and needs to be included in a filter, usually the WHERE clause, but can be GROUP BY with a HAVING.   It does 90% of the heavy lifting with index selection.
> 
> So yes, include one index with three columns and drop the other two.  You'll get the following advantages:
> 
> 1)  Good index will stay in memory longer and produce less overall I/O.
> 
> 2)  Better write performance.
> 
> Also, look at the INCLUDE syntax of index creation.  This is even better if sort order isn't necessary.  It will prevent a seek or scan on a non-clustered index from doing a key lookup or RID lookup.

**Comment by brockallen** [comment]
So from what he's saying, it sounds like just having an index on subjectid is sufficient?

**Comment by brockallen** [comment]
Ah, nevermind -- Ike said it in there -- keep the one with all 3.

**Comment by brockallen** [comment]
Done on dev.
