### ISSUE TITLE
Composite Primary Key for PersistedGrant

### ISSUE THREAD

**Issue by igarciaolaizola** [IdentityServer/IdentityServer4.EntityFramework#51]
The table generated to store `PersistedGrants` is using a Composite Primary Key (see [here](https://github.com/IdentityServer/IdentityServer4.EntityFramework/blob/dev/src/IdentityServer4.EntityFramework/Extensions/ModelBuilderExtensions.cs#L115)):

```
grant.HasKey(x => new {x.Key, x.Type});
```

However, the `PersistedGrants` are retrieved or deleted by only using the field `Key` and with a `FirstOrDefault` in order to ignore possible extra tuples. See [here ](https://github.com/IdentityServer/IdentityServer4.EntityFramework/blob/dev/src/IdentityServer4.EntityFramework/Stores/PersistedGrantStore.cs#L60)or [here](https://github.com/IdentityServer/IdentityServer4.EntityFramework/blob/dev/src/IdentityServer4.EntityFramework/Stores/PersistedGrantStore.cs#L80):
```
var persistedGrant = _context.PersistedGrants.FirstOrDefault(x => x.Key == key);
```
Shouldn't be better to use only the field `Key` as the Primary Key in order to ensure that a single tuple will be retrieved?

**Comment by scottbrady91** [comment]
Seeing as how the key is now generated using an implementation of `IHandleGenerationService` or a combination of client id and subject, I'm not too sure why there's a composite primary key. Seems to be a hangover from the previous implementation of the grant stores. It is a breaking change now though, as we're post release...

@brockallen am I missing a reason for this? Is there a likelihood of keys clashing between types to warrant a composite key?

**Comment by brockallen** [comment]
I don't have the code in front of me ATM, but I think I tried to create indexes based on the query patterns. Maybe the one in question is a hold over from the previous IS3 codebase, tho.

**Comment by scottbrady91** [comment]
This is the primary key, not the indexes. There's another issue on this repo about the indexes I've been meaning to investigate.

**Comment by brockallen** [comment]
Ah ok -- so I think the reason I did that is because the table is overloaded with different types so I supposed I was thinking of the possibility of 2 RNGs that might be the same. But good point about them only being deleted by key.

**Comment by brockallen** [comment]
Done on dev.
