### ISSUE TITLE
Entity Framework 6 on .NET Core Framework

### ISSUE THREAD

**Issue by maganuk** [IdentityServer/IdentityServer4.EntityFramework#52]
Hi,

Is it possible to use IdentityServer4.EntityFramework with EF6 running on .Net Core Framework? 

We're using EF6 code first to generate our models along with Migrator.EF6.

Thanks
Vishal

**Comment by scottbrady91** [comment]
No, Entity Framework 6 cannot run on .NET Core, it can only target the .NET Framework.

This package uses Entity Framework Core which is also not compatible with Entity Framework 6.

**Comment by maganuk** [comment]
Ok. And yes you are right, I meant we're targeting .Net Framework. Is there any other solution to use the persistent store using EF6?

**Comment by scottbrady91** [comment]
I'm not aware of any community projects to support Entity Framework 6. If you're looking to pursue this an implementation wouldn't be hard to implement. You would need the entities, mappers, dbcontexts, and stores/services for clients, resources, and persisted grants.

**Comment by maganuk** [comment]
Got it. Will give it a shot

**Comment by scottbrady91** [comment]
Let me know how it goes.

**Comment by maganuk** [comment]
@scottbrady91 I got it to work with EF6. Didn't convert the library but implemented all the code directly in my solution since we were using code first and wanted to add some additional attributes to the models. Working perfectly. Thanks a lot.

BTW do you have any idea if it is possible to extend the IClientStore interface? I want to add some additional methods for the clients.

**Comment by scottbrady91** [comment]
Sure, only the stores and services in this package use IClientStore, so you have full control since you've replicated all of the code.

**Comment by szegto** [comment]
I have same issue.
@maganuk Could you share your solution if it is possible?

**Comment by maganuk** [comment]
@szegto [This](https://github.com/IdentityServer/IdentityServer4.EntityFramework/tree/dev/src/IdentityServer4.EntityFramework) is a good starting point. I just ported all this to ef6

**Comment by szegto** [comment]
Thanks a lot.
I have already found it earlier, but I have some problem in the code.
Could you help me a little bit?
In the Startup.cs file, how can I solve the problem in this point? (???)

services.AddIdentityServer()
                .AddTemporarySigningCredential()
                .AddSecretParser<ClientAssertionSecretParser>()
                .AddSecretValidator<PrivateKeyJwtSecretValidator>()
                .AddTestUsers(TestUsers.Users)
                .AddConfigurationStore(builder =>
                    **(???)builder.UseSqlServer(connectionString, 
                        options => options.MigrationsAssembly(migrationsAssembly)))
                .AddOperationalStore(builder =>
                    (???)builder.UseSqlServer(connectionString,
                        options => options.MigrationsAssembly(migrationsAssembly)));**

What code should I replace that part?

**Comment by seven1986** [comment]
@szegto  can this help you?
```csharp
 var IdentityServerStore = new Action<DbContextOptionsBuilder>(x => 
.UseSqlServer(connectionString, 
 opts => opts.MigrationsAssembly(migrationsAssembly)));

services.AddIdentityServer()
.AddConfigurationStore(builder => builder.ConfigureDbContext = IdentityServerStore )
.AddOperationalStore(builder => builder.ConfigureDbContext = IdentityServerStore );
```
