### ISSUE TITLE
[question] Client creation date

### ISSUE THREAD

**Issue by jmurphzyo** [IdentityServer/IdentityServer4.EntityFramework#53]
Is there any plans to add a property creation date or would I just need to do a custom implementation?

**Comment by brockallen** [comment]
No plans for this. We didn't specifically design for you to extend our schema, but it might be possible. If you try it, let us know how difficult or easy it is.

**Comment by jmurphzyo** [comment]
Will do, thanks for the quick response.

**Comment by brockallen** [comment]
Any update? Can we close this issue?

**Comment by jmurphzyo** [comment]
Sorry, I ended up just doing a custom implementation.
