### ISSUE TITLE
PersistedGrants.Data column truncation

### ISSUE THREAD

**Issue by roberthannon** [IdentityServer/IdentityServer4.EntityFramework#54]
Hi I'm getting this exact issue: https://github.com/IdentityServer/IdentityServer4/issues/642. It seems like the provider I'm using (a MySQL provider called SapientGuardian.EntityFrameworkCore.MySql) is deciding that by default string properties are mapped to varchar(255) columns. I've tried the suggested solution of manually changing the column to something bigger like varchar(2048), but the data is still being truncated because of entity framework itself (I think). It looks like it truncates the string to what it _thinks_ is the column size based on the entity mapping. I assume the provider for SQL Server uses a larger default length for strings.

Would it be better if an explicit MaxLength is set for all string fields in entities? That way we don't rely on different EF providers using large text fields by default.

**Comment by scottbrady91** [comment]
What columns are having this issue?

**Comment by brockallen** [comment]
> deciding that by default string properties are mapped to varchar(255) columns

Can you let us know how this was determined?

**Comment by roberthannon** [comment]
Thanks for the reply. I'm specifically having issue with the `PersistedGrants.Data` column which is truncating the JSON data and causing authorization_code logins to fail. But I see all string columns that are missing the `HasMaxLength` constraint in their mapping are defaulting to varchar(255). Columns which have a max length specified are being created with the correct size. Here's all the defaulted fields I can find: `PersistedGrants.Data`, `Clients.LogoUri`, `Clients.LogoutUri`.

It's almost certainly the DB provider which is choosing the default: https://github.com/SapientGuardian/SapientGuardian.EntityFrameworkCore.MySql/blob/master/src/SapientGuardian.EntityFrameworkCore.MySql/MySQLTypeMapper.cs
But if I post an issue with them I'm sure they'll tell me the default is sensible and to fix by using an explicit length in my mapping.

The migrations look correct and do not specify a max length. Here's the generated PersistedGrant DB migration:

```cs
[DbContext(typeof(PersistedGrantDbContext))]
partial class PersistedGrantDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
        modelBuilder
            .HasAnnotation("ProductVersion", "1.1.0-rtm-22752");

        modelBuilder.Entity("IdentityServer4.EntityFramework.Entities.PersistedGrant", b =>
            {
                b.Property<string>("Key")
                    .HasMaxLength(200);

                b.Property<string>("Type")
                    .HasMaxLength(50);

                b.Property<string>("ClientId")
                    .IsRequired()
                    .HasMaxLength(200);

                b.Property<DateTime>("CreationTime");

                b.Property<string>("Data")
                    .IsRequired();

                b.Property<DateTime?>("Expiration");

                b.Property<string>("SubjectId")
                    .HasMaxLength(200);

                b.HasKey("Key", "Type");

                b.HasIndex("SubjectId");

                b.HasIndex("SubjectId", "ClientId");

                b.HasIndex("SubjectId", "ClientId", "Type");

                b.ToTable("PersistedGrants");
            });
    }
}
```

Here's the resulting table schema:

```sql
CREATE TABLE `persistedgrants` (
   `Key` varchar(200) COLLATE utf8_unicode_ci NOT NULL,
   `Type` varchar(50) COLLATE utf8_unicode_ci NOT NULL,
   `ClientId` varchar(200) COLLATE utf8_unicode_ci NOT NULL,
   `CreationTime` datetime NOT NULL,
   `Data` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
   `Expiration` datetime DEFAULT NULL,
   `SubjectId` varchar(200) COLLATE utf8_unicode_ci DEFAULT NULL,
   PRIMARY KEY (`Key`,`Type`),
   KEY `IX_PersistedGrants_SubjectId` (`SubjectId`),
   KEY `IX_PersistedGrants_SubjectId_ClientId` (`SubjectId`,`ClientId`),
   KEY `IX_PersistedGrants_SubjectId_ClientId_Type` (`SubjectId`,`ClientId`,`Type`)
 ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci
```

The easiest solution to me seems like to add explicit max length constraints to all string fields.

The other solution would be for me to modify the mapping somehow, but I'm not sure if there's an extensibility point to do that (I'm relatively new to EF).

**Comment by brockallen** [comment]
What's the longest MySql can handle? Do they have a TEXT equivalent like a SQL Server DB would?

**Comment by roberthannon** [comment]
> Before Mysql version 5.0.3 Varchar datatype can store 255 character, but from 5.0.3 it can be store 65,535 characters. BUT it has a limitation of maximum row size of 65,535 bytes. It means including all columns it must not be more than 65,535 bytes.

There is also a `TEXT` type and I think it has the same max size of 65,535 bytes.

It looks like the SQL Server provider defaults the length to 4000 or 8000 (depending on if is unicode or not): https://github.com/aspnet/EntityFramework/blob/dev/src/Microsoft.EntityFrameworkCore.SqlServer/Storage/Internal/SqlServerMaxLengthMapping.cs

**Comment by roberthannon** [comment]
This is the PersistedGrants table after migrating a fresh SQL Server DB:

```sql
CREATE TABLE [dbo].[PersistedGrants] (
    [Key]          NVARCHAR (200) NOT NULL,
    [Type]         NVARCHAR (50)  NOT NULL,
    [ClientId]     NVARCHAR (200) NOT NULL,
    [CreationTime] DATETIME2 (7)  NOT NULL,
    [Data]         NVARCHAR (MAX) NOT NULL,
    [Expiration]   DATETIME2 (7)  NULL,
    [SubjectId]    NVARCHAR (200) NULL,
    CONSTRAINT [PK_PersistedGrants] PRIMARY KEY CLUSTERED ([Key] ASC, [Type] ASC)
);
```

I'm not sure what `NVARCHAR (MAX)` is, but may be bigger than 4000/8000 chars.

**Comment by roberthannon** [comment]
Would changing the mapping to this be acceptable?:
```
grant.Property(x => x.Data).HasMaxLength(50000).IsRequired();
```

Or do you think that's not large enough?

**Comment by brockallen** [comment]
Once we get to our next round of releases, I'll include something here for this.

**Comment by brockallen** [comment]
This is covered [here](https://docs.microsoft.com/en-us/ef/core/modeling/max-length) in the docs. I don't like that it's ambiguous by design from Microsoft.

**Comment by brockallen** [comment]
Ok, done. I set it to 50k. Interestingly, on SqlServer this magically turns into nvarchar(max).

Can you test please on MySql?

**Comment by herkyg** [comment]
@brockallen The .HasMaxLength(50000) solution doesn't turn out to work in MySql. I found that the value of HasMaxLength(N) is honored (as a varchar(N)) if set to anything less than 8000. If set to exactly 8000, the column is created as longtext, and anything larger than 8000 turns into varchar(255)!

If the HasMaxLength call is left out entirely, the default is longtext. The workaround I'm thinking of using is adding .HasColumnType("text(50000)"), which results in a column type of mediumtext, which seems the most appropriate, although just leaving it out might be just as good.

**Comment by roberthannon** [comment]
@herkyg Which MySQL provider are you using? I'm getting a different issue with SapientGuardian.EntityFrameworkCore.MySql but either way I don't think Identity Server should implement any further work arounds. The providers should handle `.HasMaxLength(50000)` with `VARCHAR(50000)` or fallback to `TEXT` if that value is too long for VARCHAR.

**Comment by brockallen** [comment]
Sounds like an issue to be brought up with the MySql maintainers.
