### ISSUE TITLE
PersistedGrants table constantly grows

### ISSUE THREAD

**Issue by ravetroll** [IdentityServer/IdentityServer4.EntityFramework#59]
I noticed my database size constantly expanding quite fast and found that the PersistedGrants table is the culprit.  I was wondering if It should be clearing out expired tokens? Is there any plan to build in a function to clear out old tokens?

**Comment by scottbrady91** [comment]
Yep, check out [this line](https://github.com/IdentityServer/IdentityServer4.EntityFramework/blob/dev/src/Host/Startup.cs#L81) in the example host.

**Comment by ravetroll** [comment]
And just today I had finished implementing my own solution..... Oh well!
