### ISSUE TITLE
Client entity is always INSERTed

### ISSUE THREAD

**Issue by antonfelich** [IdentityServer/IdentityServer4.EntityFramework#60]
We have implemented an administrator interface for Clients/RedirectUris/Secrets etc... I'm probably missing something basic, but the problem I'm having is: -

I load a IdentityServer4.EntityFramework.Entities.Client from a Postgres DB and then call .ToModel() on it before passing an IdentityServer4.Models.Client back to the UI layer for rendering. 

Since the IdentityServer4.Models.Client doesn't have an ID property on it there is nothing for AutoMapper to copy over. So when the time comes to submit the form and save the client the ConfigurationDbContext will always treat it as a new object and do an INSERT.

Following the IntegrationTests in the source I would imagine a test looking something similar to this: -

        public void FindClientByIdAsync_WhenClientExists_AddARedirectUrl(DbContextOptions<ConfigurationDbContext> options)
        {
            var testClient = new Client
            {
                ClientId = "test_client",
                ClientName = "Test Client"
            };

            using (var context = new ConfigurationDbContext(options, StoreOptions))
            {
                context.Clients.Add(testClient.ToEntity());
                context.SaveChanges();
            }

            Client client;
            using (var context = new ConfigurationDbContext(options, StoreOptions))
            {
                var store = new ClientStore(context, FakeLogger<ClientStore>.Create());
                client = store.FindClientByIdAsync(testClient.ClientId).Result;
            }
			            
			using (var context = new ConfigurationDbContext(options, StoreOptions))
			{
				client.RedirectUris.Add("www.google.com");
                context.Clients.Add(testClient.ToEntity());
                context.SaveChanges();
			}

            Assert.NotNull(client);
        }

**Comment by scottbrady91** [comment]
I'm surprised this is happening, as there is a [unique constraint on the `ClientId`](https://github.com/IdentityServer/IdentityServer4.EntityFramework/blob/dev/src/IdentityServer4.EntityFramework/Extensions/ModelBuilderExtensions.cs#L36), so it should be erroring for you because of that.

Either way, that integration test is trying to add the same entity to the context twice, so it's going to fail. It looks like you're trying to update an existing entity in the database, so you want something like this in your code:

```
using (var context = new ConfigurationDbContext(options, StoreOptions)) {
    client = await context.First(x => x.ClientId == testClient.ClientId); // entity connected to the dbcontext
    client.RedirectUris.Add(new ClientRedirectUri {RedirectUri = "www.google.com"});
    context.SaveChanges();
}
```

**Comment by brockallen** [comment]
@antonfelich any update from @scottbrady91's suggestion?

**Comment by antonfelich** [comment]
Yep @scottbrady91 was spot on, I had my contexts mixed up, as soon as I separated the test into two units of work (to replicate the real world) everything was fine. 

Been doing nHibernate forever so adjusting to EF is hurting my brain :) 

Thanks @scottbrady91
