### ISSUE TITLE
Interaction Generator Error

### ISSUE THREAD

**Issue by rh78** [IdentityServer/IdentityServer4.EntityFramework#61]
Hi, in my logs (Application Insights, running on Azure, ASP.NET Core on full .NET 4.6.2 Framework) I sometimes get "Interaction Generator Error" (no exception, no stack trace, just a log entry with severity level "Error"). Category Name "IdentityServer4.Endpoints.AuthorizeEndpoint" on "GET /connect/authorize"

Reporting because maybe it is an issue, but in any case it would be good to know possible causes of this issue.

**Comment by scottbrady91** [comment]
Shouldn't this be in the main repo?

**Comment by rh78** [comment]
Sorry!
