### ISSUE TITLE
Error in Update Db: duplicate key value violates unique constraint "IX_ApiScopes_Name"

### ISSUE THREAD

**Issue by dudedev** [IdentityServer/IdentityServer4.EntityFramework#63]
I have implemented an API to manage API Resources of IdentityServer (IdentityServer4). 
If I try to update an API Resource, I get this database error. **"duplicate key value violates unique constraint "IX_ApiScopes_Name".**

Code to update database:
```
        public void Update(IdentityServer4.Models.ApiResource apiResource)
        {
            _context.ApiResources.Update(apiResource.ToEntity());
            _context.SaveChanges();
        }
```
To test the update method, I get the ApiResource using get method and just change the description/displayName of the received model, and send it back to update endpoint.
```
{
  "enabled": true,
  "name": "api1",
  "displayName": "Updated display name",
  "description": null,
  "apiSecrets": [],
  "userClaims": [],
  "scopes": [
    {
      "name": "api1",
      "displayName": "My API",
      "description": null,
      "required": false,
      "emphasize": false,
      "showInDiscoveryDocument": true,
      "userClaims": []
    }
  ]
}
```
If I remove the scopes part and just change the displayName, then I get following error: 
```
Database operation expected to affect 1 row(s) but actually affected 0 row(s). Data may have been modified or deleted since entities were loaded. See http://go.microsoft.com/fwlink/?LinkId=527962 for information on understanding and handling optimistic concurrency exceptions.
```

**Comment by brockallen** [comment]
Is `Update` supposed to understand that the entity you pass should map to an existing instance in the DB?

**Comment by dudedev** [comment]
Yes, you are right. It should not. the mapped entity (apiResource.ToEntity()) does not contain valid 'Id'   and that is why it does know which row to update. Sorry for the stupid question. But, What is the best way to update the changed fields.  Should I check each fields individually to see it has changed and then update the entity model?

**Comment by brockallen** [comment]
Load the one you want, then update the properties. Do we have an API for mapping to an existing one?

**Comment by brockallen** [comment]
Or there's some API in EF to say "track" or somesuch. In fact, all of these questions you should be checking from the EF Core docs -- you don't want me to be telling you how to do this :)

**Comment by dudedev** [comment]
:-) Thank you. will check EF core docs to find something. For now, it seems less work to simply delete and create a new one.
