### ISSUE TITLE
Add to config extension methods so EF can be added to any asp.net core host

### ISSUE THREAD

**Issue by brockallen** [IdentityServer/IdentityServer4.EntityFramework#64]
For example, an API that just wants to use this EF library to host config DB and/or operational DB.

**Comment by brockallen** [comment]
This will not need to register the stores.

**Comment by scottbrady91** [comment]
Isn't this just wrappers around a couple of `AddDbContext`'s?

**Comment by brockallen** [comment]
yea, but some people need it

**Comment by brockallen** [comment]
ok yea, due to laziness on my part i'll punt

**Comment by leastprivilege** [comment]
You can use the `AddIdentityServerBuilder` method to get a builder, and then use the standard ext method to register the stores I think.
