### ISSUE TITLE
Consider adding normalized names for lookups

### ISSUE THREAD

**Issue by brockallen** [IdentityServer/IdentityServer4.EntityFramework#67]
Id Name, Scope name, Client id?

**Comment by brockallen** [comment]
@scottbrady91 @leastprivilege So I have identified for this:

Clients => NormalizedClientId
ApiResource => NormalizedName
ApiScope => NormalizedName
IdentityResource => NormalizedName
PersistedGrant => NormalizedClientId and NormalizedSubjectId

Do those really make sense? Should client/scope names be case-insensitive? Should SubjectIds also be case-insensitive? 

Why/who asked for this feature? Is there a real use-case here?

**Comment by scottbrady91** [comment]
This was to handle case sensitivity between db providers. The normalized approach is what the ASP.NET Core Identity library does.

Implementer should be able to register their own normalizer, with the default implementation just uppercasing the values.

**Comment by brockallen** [comment]
When would someone need to replace it?

**Comment by brockallen** [comment]
Given that we don't have an API to create these, I'm finding it hard to have a hook to do the normalization, unless I hard code it in the properties somehow (which means not from DI).

**Comment by brockallen** [comment]
Ok, PR here. Have a look: https://github.com/IdentityServer/IdentityServer4.EntityFramework/pull/96

**Comment by brockallen** [comment]
Do we normalize keys? Subject ids? This is becoming complicated and potentially a security issue.

**Comment by brockallen** [comment]
Killing this, as it seems like a rat's nest.
