### ISSUE TITLE
Scaffolding Controllers with AspNetCore apps

### ISSUE THREAD

**Issue by cjhoward92** [IdentityServer/IdentityServer4.EntityFramework#68]
Is there some mechanism that I can use to scaffold controllers and views for the IdentityServer4 DbContexts? 

We are building a centralized SSO portal with IdentityServer4 for all of our intranet apps and we will be managing new resources through a UI, probably via the IdentityServer4 UI itself. For example, we may deploy a new app and decide that a new ApiResource is needed. Our support staff will log into the identity server and add a new ApiResource from the MVC application itself.

If we could scaffold views and controllers from the existing entities belonging to the ConfigurationDbContext that would save a lot of time. While we don't use the default scaffold, it obviously gets a lot of the boilerplate work done for us. Either that or have some sort of template generator.

Wasn't sure which repo to ask this question in. I am also not sure if this is a common thing, adding resources via an interface of some sort, or if people just populate them into the database directly.

**Comment by brockallen** [comment]
I don't have anything for you other than what the ASP.NET Core and VS tooling offer. There is a commercial product that already has a UI for these things: https://www.identityserver.com/upcoming-products/

**Comment by cjhoward92** [comment]
Ok, thanks for clearing that up.
