### ISSUE TITLE
Column truncation Entity Framework MySQL

### ISSUE THREAD

**Issue by BadTactx** [IdentityServer/IdentityServer4.EntityFramework#72]
Hey team,

I'm not sure if this is an issue with in IdentityServer4.EntityFramework or whether it's with the MySql connector for EntityFrameworkCore (MySql.Data.EntityFrameworkCore) but I thought I'd leave this here in case it's useful to someone?

When generating migrations, I noticed that mysql was ignoring the max length settings that you'd applied with in ModelBuilderExtensions.cs

Scripting a migration based on this file generated the following SQL

```
IF EXISTS(SELECT 1 FROM information_schema.tables
  WHERE table_name = '
__EFMigrationsHistory' AND table_schema = DATABASE())
BEGIN
CREATE TABLE `__EFMigrationsHistory` (
    `MigrationId` nvarchar(150) NOT NULL,
    `ProductVersion` nvarchar(32) NOT NULL,
    PRIMARY KEY (`MigrationId`)
);

END;

CREATE TABLE `PersistedGrants` (
    `Key` nvarchar(200) NOT NULL,
    `ClientId` nvarchar(200) NOT NULL,
    `CreationTime` datetime NOT NULL,
    `Data` varchar(255) NOT NULL,
    `Expiration` datetime,
    `SubjectId` nvarchar(200),
    `Type` nvarchar(50) NOT NULL,
    PRIMARY KEY (`Key`)
);

CREATE INDEX `IX_PersistedGrants_SubjectId_ClientId_Type` ON PersistedGrants (`SubjectId`, `ClientId`, `Type`);

INSERT INTO `__EFMigrationsHistory` (`MigrationId`, `ProductVersion`)
VALUES ('20170510215657_InitialIdentityServerMigration', '1.1.2');
```

Note that Data generates sql for a max length of 255 rather than the 50,000 specified in the ModelBuilderExtensions.cs - this only appears to happen if the value is set higher than 255 (note that other field lengths have been correctly set)

I adjusted the code with in ModelBuilderExtensions.cs to the following

`grant.Property(x => x.Data).HasColumnType("text").HasMaxLength(50000).IsRequired();`

which when scripted as a migration generates correctly as 

```
IF EXISTS(SELECT 1 FROM information_schema.tables
  WHERE table_name = '
__EFMigrationsHistory' AND table_schema = DATABASE())
BEGIN
CREATE TABLE `__EFMigrationsHistory` (
    `MigrationId` nvarchar(150) NOT NULL,
    `ProductVersion` nvarchar(32) NOT NULL,
    PRIMARY KEY (`MigrationId`)
);

END;

CREATE TABLE `PersistedGrants` (
    `Key` nvarchar(200) NOT NULL,
    `ClientId` nvarchar(200) NOT NULL,
    `CreationTime` datetime NOT NULL,
    `Data` text NOT NULL,
    `Expiration` datetime,
    `SubjectId` nvarchar(200),
    `Type` nvarchar(50) NOT NULL,
    PRIMARY KEY (`Key`)
);

CREATE INDEX `IX_PersistedGrants_SubjectId_ClientId_Type` ON PersistedGrants (`SubjectId`, `ClientId`, `Type`);

INSERT INTO `__EFMigrationsHistory` (`MigrationId`, `ProductVersion`)
VALUES ('20170510215657_InitialIdentityServerMigration', '1.1.2');
```

I'm not sure whether this is compatible with other providers or not?

**Comment by Mardoxx** [comment]
Related [lines](https://github.com/IdentityServer/IdentityServer4.EntityFramework/blob/db8e5320e30dff65f92d89698545f5220607276f/src/IdentityServer4.EntityFramework/Extensions/ModelBuilderExtensions.cs#L113-L115) for reference.

Not a MySQL expert, but from my limited use of it you don't specify length constraints on text fields. I believe perhaps this constraint has been chosen is to assist migration between MSSQL and MySQL? Unsure.

See also: http://stackoverflow.com/a/22061495/3515174

**Comment by brockallen** [comment]
All set on this issue -- can we close?
