### ISSUE TITLE
ASP.NET Core Template for EntityFramework

### ISSUE THREAD

**Issue by muqeet-khan** [IdentityServer/IdentityServer4.EntityFramework#75]
Can you have a template for IS 4 entityframework in ASP.NET Core? I think it will be really beneficial for everyone even as part of quickstarts. 

Similar to: dotnet new is4inmem 
Example: dotnet new is4ef

**Comment by muqeet-khan** [comment]
cc @brockallen

**Comment by leastprivilege** [comment]
agreed

**Comment by brockallen** [comment]
Work started here: https://github.com/IdentityServer/IdentityServer4.Templates/tree/dev/src/IdentityServer4EntityFramework, so I'll close this.
