### ISSUE TITLE
ClientId string property foreign key PersistentGrant table

### ISSUE THREAD

**Issue by Wsteppe** [IdentityServer/IdentityServer4.EntityFramework#76]
Hi, so I'm comparing the Client and Persistent Grant tables.

The PersistentGrant table has a link to the Client table:

    public class PersistedGrant
    {
        public string Key { get; set; }
        public string Type { get; set; }
        public string SubjectId { get; set; }
        public string **ClientId** { get; set; }
        public DateTime CreationTime { get; set; }
        public DateTime? Expiration { get; set; }
        public string Data { get; set; }
    }

    public class Client
    {
        public int Id { get; set; }

        public string **ClientId** { get; set; }
    }

However, why is the ClientId column in the PersistentGrant table a String field? Should it not link to the Client int Id primary key? I see no unique constraint on the Client ClientId field, so its uniqueness is not enforced anywhere. Can this not cause problems? We can enforce this in our database model, but it just seems so awkward.

**Comment by Wsteppe** [comment]
More to the point, if the Client-ClientId field is meant to be a unique (primary?) key, then why is another int field used as a primary key?

**Comment by scottbrady91** [comment]
Check out #22 for some previously discussed reasoning behind this.

Just had a quick scan and there's a [unique index on ClientId](https://github.com/IdentityServer/IdentityServer4.EntityFramework/blob/dev/src/IdentityServer4.EntityFramework/Extensions/ModelBuilderExtensions.cs#L36).
