### ISSUE TITLE
Testing repository relying on ConfigurationDbContext

### ISSUE THREAD

**Issue by blgrnboy** [IdentityServer/IdentityServer4.EntityFramework#77]
I am using the repository pattern within my implementation, and adding an ApiResourceRepository.  Here is a sample of that:

```
public class ApiResourceRepository : IApiResourceRepository
{
	private readonly IServiceProvider _serviceProvider;

	public ApiResourceRepository(IServiceProvider serviceProvider)
	{
		_serviceProvider = serviceProvider;
		_dbSettings = dbSettings;
	}

	public async Task<ApiResource> Get(int id)
	{
		ApiResource result;

		using (var serviceScope = _serviceProvider.CreateScope())
		{
			var context = serviceScope.ServiceProvider.GetRequiredService<ConfigurationDbContext>();
			result = await
				context.ApiResources
				.Include(x => x.Scopes)
				.Include(x => x.UserClaims)
				.FirstOrDefaultAsync(x => x.Id == id);
		}

		return result;
	}
}
```

Is this the suggested way of obtaining/working with a `ConfigurationDbContext`?

I am also struggling with my integration tests, because it seems like I would have to mock an IServiceProvider that can provide an instance of the `ConfigurationDbContext`?  How do you address these concerns?

**Comment by scottbrady91** [comment]
You shouldn't be injecting `IServiceProvider`, instead you should directly inject the dependency you want, in this case `ConfigurationDbContext` or `IConfigurationDbContext`.

See https://github.com/IdentityServer/IdentityServer4.EntityFramework/blob/dev/src/IdentityServer4.EntityFramework/Stores/ClientStore.cs for a good example.
