### ISSUE TITLE
Stores implementation doesn't leverage the async capabilities of EF

### ISSUE THREAD

**Issue by ItielBeeri** [IdentityServer/IdentityServer4.EntityFramework#79]
I have noticed that stores are implemented using `Task.FromResult(result)` style.
Since these stores are all about DB operations, I would expect a use of the async versions of LINQ / DbContext methods, so they could be truly non-blocking (depend on the underlying data provider implementation, of course). For [example](https://github.com/IdentityServer/IdentityServer4.EntityFramework/blob/dev/src/IdentityServer4.EntityFramework/Stores/PersistedGrantStore.cs#L58), rather than
```C#
public Task<PersistedGrant> GetAsync(string key)
{
    var persistedGrant = _context.PersistedGrants.FirstOrDefault(x => x.Key == key);
    var model = persistedGrant?.ToModel();
    return Task.FromResult(model);
}
```
I would expect 
```C#
public async Task<PersistedGrant> GetAsync(string key)
{
    var persistedGrant = await _context.PersistedGrants.FirstOrDefaultAsync(x => x.Key == key);
    var model = persistedGrant?.ToModel();
    return model;
}
```
I would like to know if there was a deliberate decision to implement it this way.

**Comment by brockallen** [comment]
At the time we first built this library, the async support in EF was not really considered "ready for production".

**Comment by brockallen** [comment]
I just pushed a branch for this, but unfortunately they are suffering from the same problems we had in IS3 under load -- IOW, we start failing because the number of connections in the pool is exhausted much faster.

**Comment by brockallen** [comment]
I don't see us adding this, as it pushes a lot more onto the DB that most people are ready to tune for.
