### ISSUE TITLE
Cannot insert explicit value for identity column in table 'Clients' when IDENTITY_INSERT is set to OFF.

### ISSUE THREAD

**Issue by Jenan** [IdentityServer/IdentityServer4.EntityFramework#81]
Hello,

I want to create new client secret for existing Client like this:

I get this error: `SqlException: Cannot insert explicit value for identity column in table 'Clients' when IDENTITY_INSERT is set to OFF.`

```
public async Task<int> AddClientSecret(ClientSecretsDTO clientSecret)
{
//entity = new ClientSecret(){ Value = "HASH", Client = new Client { Id = 1 } }
var entity = clientSecret.ToEntity();

await _dbContext.ClientSecrets.AddAsync(entity); => ERROR - SqlException: Cannot insert explicit value for identity column in table 'Clients' when IDENTITY_INSERT is set to OFF.

return await _dbContext.SaveChangesAsync();
}
```

How can I fix this issue?
Thx.

**Comment by brockallen** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue.

Please use StackOverflow for that. This has the advantage that questions and answers can be easily found by search engines, and that there are more people answering questions than just us.

For IdentityServer3
https://stackoverflow.com/questions/tagged/?tagnames=identityserver3&sort=newest

For IdentityServer4
https://stackoverflow.com/questions/tagged/?tagnames=identityserver4&sort=newest

For commercial support
https://identityserver.io/
