### ISSUE TITLE
Constraints on PersistedGrants table

### ISSUE THREAD

**Issue by vandenbergjp** [IdentityServer/IdentityServer4.EntityFramework#83]
I'm writing a custom implementation of the IPersistedGrantStore. For reference I'm looking at the table created by the Entity Framework migrations. See below.

Looking at the table I have three questions:
1. Shouldn't there be a foreign key constrain between the ClientId in this table and the ClientId column in the Client table
2. Shouldn't the SubjectId column be NOT NULL
3. Shouldn't the index on SubjectId, ClientId, Type be unique?

```sql
CREATE TABLE [IdentityServer4.QuickStart.EntityFramework].dbo.PersistedGrants (
  [Key] nvarchar(200) NOT NULL,
  ClientId nvarchar(200) NOT NULL,
  CreationTime datetime2 NOT NULL,
  Data nvarchar(max) NOT NULL,
  Expiration datetime2 NULL,
  SubjectId nvarchar(200) NULL,
  Type nvarchar(50) NOT NULL,
  CONSTRAINT PK_PersistedGrants PRIMARY KEY CLUSTERED ([Key])
)
ON [PRIMARY]
TEXTIMAGE_ON [PRIMARY]
GO

CREATE INDEX IX_PersistedGrants_SubjectId_ClientId_Type
  ON [IdentityServer4.QuickStart.EntityFramework].dbo.PersistedGrants (SubjectId, ClientId, Type)
  ON [PRIMARY]
GO
```

**Comment by brockallen** [comment]
> Shouldn't there be a foreign key constrain between the ClientId in this table and the ClientId column in the Client table

We designed the operational data and config data be decoupled from one another -- IOW they can't assume each are in the same DB.

> Shouldn't the SubjectId column be NOT NULL

A client credentials client might use reference tokens.

> Shouldn't the index on SubjectId, ClientId, Type be unique?

A user might run the same client on 2 devices.

**Comment by vandenbergjp** [comment]
Thanks for your quick response! I was almost certain that there was a reason for this design, but I did not have enough knowledge of the internals to come up with a good explaination myself.
