### ISSUE TITLE
Consider moving non-filtering properties to a JSON/blob column

### ISSUE THREAD

**Issue by brockallen** [IdentityServer/IdentityServer4.EntityFramework#85]
To better deal with schema changes in the future. Thoughts? @leastprivilege @scottbrady91

**Comment by scottbrady91** [comment]
Because EF migrations are hard?

Maybe a a library for document databases would have the same affect.

**Comment by brockallen** [comment]
> Because EF migrations are hard?

For some, yes. For others, tedious and with little value given that much of this data is never used to filter.

**Comment by scottbrady91** [comment]
Okay. This repo uses the EF Relational library. Maybe it's worthwhile revisiting making another persistence library without that? Aimed at NoSQL databases or just taking this approach?

**Comment by brockallen** [comment]
Yep, possibly.

**Comment by brockallen** [comment]
Yea, since most people are using sql server mgmt studio to edit, we'll not do this.
