### ISSUE TITLE
IdentityServer4 2.0.0-preview

### ISSUE THREAD

**Issue by giovanibarili** [IdentityServer/IdentityServer4.EntityFramework#86]
Hi!

With the new version of IdentityServer4, when startup the system, showed the error with method ResourceStore.GetAllResources, because in this new version these method was renamed to GetAllResourcesAsync

I willed try update IdentityServer4 to 2.0.0-preview, mas has conflict with netstandar, it's need netcoreapp2.0.

**Comment by scottbrady91** [comment]
Hi, this package hasn't been updated to ASP.NET Core 2.x yet. It should be ready to do so once 2.0 is released and IdentityServer 4 is ready.

**Comment by StefanKert** [comment]
@scottbrady91 Do you have a roadmap for the netcore2.0 release (or preview)?

**Comment by Al4ric** [comment]
Netcore2.0 is released.

**Comment by GoodboyYmh** [comment]
@Al4ric where?

**Comment by xrkolovos** [comment]
IdentityServer4.EntityFramework-preview3 in nuget? :)

**Comment by MesfinMoges** [comment]
@xrkolovos I don't think it's ready yet; I've been keeping an eye on it as I'm trying to upgrade my project to IdentityServer4 2.0.0-preview3 and getting errors when running ef Migrations commands on ConfigurationDbContext. Here's what I did to my local copy of IdentityServer4.EntityFramework  project as a work around for now: 

 - update the project runtime target to netstandard2.0; net461
- update the nuget dependencies to the latest ones (IdentityServer4, EntitiyFrameworkCore and EntitiyFrameworkCore.Rational
- Implement the newly renamed method GetAllResourcesAsync in ResourceStore class

Hope this helps.

**Comment by Al4ric** [comment]
I was referring to this comment " It should be ready to do so once 2.0 is released and IdentityServer 4 is ready.". And I was talking about .Net Core 2.0 from Microsoft not IdentityServer4. Since 2.0 is now released all identity server should be upgraded.

There are some major, breaking changes in Core 2.0 in Identity part, so some changes are also required in IdentityServer4. I would love to have some migration documentation.

**Comment by scottbrady91** [comment]
Sure, .NET Core 2.0 is ready, but IdentityServer 4 isn't. We can't update the supporting libraries until the core library is ready.

We're looking to have more news over the next couple of weeks.

**Comment by Al4ric** [comment]
@scottbrady91 Thank You for the update.

**Comment by brockallen** [comment]
Work is mainly done on dev. We'll release a preview/rc this week.
