### ISSUE TITLE
What is the best way to add extra properties in the models

### ISSUE THREAD

**Issue by xrkolovos** [IdentityServer/IdentityServer4.EntityFramework#88]
I have this quetion. 
What would be the best way to add extra properties in this models? I don't want to re-implement this package because if you decide to add a flied in IS and add it in the models(e.x. in the Client class) i should track this changes.  
So, what would be the best option of using this package and extend some model classes?

**Comment by xrkolovos** [comment]
#89

**Comment by brockallen** [comment]
We've come up with this as the compromise: https://github.com/IdentityServer/IdentityServer4/issues/1457

It's meant to be a simple built-in way to add additional client stuff. If you need a full Db schema for the additional stuff, then, as we've always suggested, create a separate model/entity/table with a FK to the client.
