### ISSUE TITLE
InvalidOperationException: Grant types list is empty - AutoMapper

### ISSUE THREAD

**Issue by Janidbest** [IdentityServer/IdentityServer4.EntityFramework#93]
Client.ToModel() automapper extension is having an issue when the grantypes are empty. 

System may not have a client without grants however this one looks like an exception coming from automapper.

AutoMapper.AutoMapperMappingException: 'Error mapping types.'
InvalidOperationException: Grant types list is empty

[ClientMappers.cs](https://github.com/IdentityServer/IdentityServer4.EntityFramework/blob/dev/src/IdentityServer4.EntityFramework/Mappers/ClientMappers.cs)

**Comment by kieronlanning** [comment]
@Janidbest Did you find a way around this?

**Comment by brockallen** [comment]
Fixed on dev. Thanks.
