### ISSUE TITLE
No DbContext named 'PersistedGrantDbContext' was found

### ISSUE THREAD

**Issue by Cuiqs76** [IdentityServer/IdentityServer4.EntityFramework#99]
I run dotnet ef migrations add InitialIdentityServerPersistedGrantDbMigration -c PersistedGrantDbContext -o Data/Migrations/IdentityServer/PersistedGrantDb.  I get a error as blow

An error occurred while calling method 'BuildWebHost' on class 'Program'. Continuing without the application service provider. Error: One or more errors occurred. (Invalid object name 'Clients'.)
No DbContext named 'PersistedGrantDbContext' was found.

`<PackageReference Include="IdentityServer4.AspNetIdentity" Version="2.0.0-rc1" />
<PackageReference Include="IdentityServer4.EntityFramework" Version="2.0.0-rc1" />`

**Comment by kostebudinoski** [comment]
I guess, you need to specify the whole namespace in the context parameter:

-c IdentityServer4.EntityFramework.DbContexts.PersistedGrantDbContext

Also, I have a question to @Identity team, if you guys plan to support design-time DbContext discovery:

https://github.com/aspnet/Announcements/issues/258

Thanks for the amazing job you are doing!

**Comment by ThatDeveloper** [comment]
I can't execute Add-Migration or Update-Database. It just does not work. PacketManager looks like he is executing something but does not throw an error. I followed this Link:
http://docs.identityserver.io/en/release/quickstarts/8_entity_framework.html

And I tried the solution in here.

Greets Manuel

**Comment by ThatDeveloper** [comment]
Is this maybe a version conflict of .NET Core 1 and 2? @brockallen @leastprivilege

**Comment by brockallen** [comment]
Yea, not sure. I'd say look at our sample host and compare.

**Comment by ThatDeveloper** [comment]
I already spent 2 days figuring out how to. I even copied the Migrations of the Host and added them to the project but there is a version conflict with Properties nit available.
I am so excited for using .NET Core 2 with IS4.

**Comment by ThatDeveloper** [comment]
SqlException: Ungültiger Spaltenname "LogoutSessionRequired".
Ungültiger Spaltenname "LogoutUri".

Translated: Invalid column name

**Comment by brockallen** [comment]
> (I used your generated .sql files you added 11 hours before @brockallen )

Well, those are on the dev branch and are for the dev code, not necessary what's in rc1.

**Comment by sstriano** [comment]
I am seeing this exact issue as well. I have tried to fully qualify the namespaces on the context's to no avail.

**Comment by brockallen** [comment]
You're using the release version? Can you compare what you're doing to the functioning EF quickstart?

**Comment by sstriano** [comment]
Here is my project file:

```
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netcoreapp2.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="wwwroot\" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="IdentityServer4" Version="2.0.0" />
    <PackageReference Include="IdentityServer4.EntityFramework" Version="2.0.0" />
    <PackageReference Include="Microsoft.ApplicationInsights.AspNetCore" Version="2.1.1" />
    <PackageReference Include="Microsoft.AspNetCore" Version="2.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="2.0.0" />
  </ItemGroup>

  <ItemGroup>
    <DotNetCliToolReference Include="Microsoft.EntityFrameworkCore.Tools.DotNet" Version="2.0.0" />
  </ItemGroup>

</Project>

```

**Comment by brockallen** [comment]
I suspect you have code in the app that connects to the DB that's throwing. IOW, a line like this that's not commented out: https://github.com/IdentityServer/IdentityServer4.Samples/blob/release/Quickstarts/8_EntityFrameworkStorage/src/QuickstartIdentityServer/Startup.cs#L77

**Comment by meron1122** [comment]
@sstriano  , @brockallen 
I have this issue too, I don't have in startup.cs any DB process code.

`using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Hosting;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Logging;
using Server.Database;

namespace Server
{
    public class Startup
    {             
        public Startup(IHostingEnvironment env)
        {
            var builder = new ConfigurationBuilder()
                .SetBasePath(env.ContentRootPath)
                .AddJsonFile("appsettings.json", optional: false, reloadOnChange: true)
                .AddJsonFile($"appsettings.{env.EnvironmentName}.json", optional: true)
                .AddEnvironmentVariables();
            Configuration = builder.Build();
        }

        public IConfigurationRoot Configuration { get; }



        // This method gets called by the runtime. Use this method to add services to the container.
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddCors(options =>
            {
                options.AddPolicy("CorsPolicy",
                    builder => builder.AllowAnyOrigin()
                        .AllowAnyMethod()
                        .AllowAnyHeader()
                        .AllowCredentials());
            });
            
            const string connectionString = "XXXXXXX";
//            services.AddDbContext<DBContext>(options => options.UseSqlServer(("XXXXX")));
            services.AddDbContext<DBContext>(options => options.UseSqlServer((connectionString)));
            // Add framework services.
            services.AddMvc();
            services.AddAuthorization();
                        

            var migrationsAssembly = typeof(Startup).GetTypeInfo().Assembly.GetName().Name;
            //identity server
            services.AddIdentityServer()
                .AddDeveloperSigningCredential() //todo dev
                // this adds the config data from DB (clients, resources)
                .AddConfigurationStore(options =>
                {
                    options.ConfigureDbContext = builder =>
                        builder.UseSqlServer(connectionString,
                            sql => sql.MigrationsAssembly(migrationsAssembly));
                })
                // this adds the operational data from DB (codes, tokens, consents)
                .AddOperationalStore(options =>
                {
                    options.ConfigureDbContext = builder =>
                        builder.UseSqlServer(connectionString,
                            sql => sql.MigrationsAssembly(migrationsAssembly));

                    // this enables automatic token cleanup. this is optional.
                    options.EnableTokenCleanup = true;
                    options.TokenCleanupInterval = 30;
                });
            
            
            services.AddAuthentication("Bearer")
                .AddIdentityServerAuthentication(options =>
                {
                    options.Authority = "http://localhost:5000";
                    options.RequireHttpsMetadata = false;

                    options.ApiName = "api1";
                });
            

            return;
            
        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory)
        {
            loggerFactory.AddConsole(Configuration.GetSection("Logging"));
            loggerFactory.AddDebug();

            //identity server
            app.UseAuthentication();
            app.UseIdentityServer();

            app.UseCors("CorsPolicy");
            app.UseMvc();
        }
    }
}
`

**Comment by Damarus999** [comment]
Make sure you update your Program.cs per the migration guide (https://docs.microsoft.com/en-us/aspnet/core/migration/1x-to-2x/) as using the old .NET Core 1 method in a .NET Core 2 app will break EF migrations.

**Comment by janpieterz** [comment]
To add some more context to this, try running the `ef` command with the `-v` option.
I found out, through that, that it needs the static method `IWebHost BuildWebHost(string[] args)` in `Program.cs`.  See https://github.com/aspnet/EntityFrameworkCore/issues/9415#issuecomment-327589912

**Comment by jackfacts** [comment]
I ran into this same issue when running with a .net47 project and ef core. I think the ef cli is slightly different for the two frameworks. For instance I am unable to get any of the dotnet ef  commands to work, but the Add-Migration, Update-Database, etc do.

Either way I was able to solve this, by creating new contexts that inherit from the ConfigurationDbContext and PersistedGrantDbContext.

```csharp
public class ConfigurationDbContext : IdentityServer4.EntityFramework.DbContexts.ConfigurationDbContext
{
        public ConfigurationDbContext(DbContextOptions<IdentityServer4.EntityFramework.DbContexts.ConfigurationDbContext> options, ConfigurationStoreOptions storeOptions) : base(options, storeOptions)
        {
        }
}
```

```csharp
public class PersistedGrantDbContext : IdentityServer4.EntityFramework.DbContexts.PersistedGrantDbContext
{
    public PersistedGrantDbContext(DbContextOptions<IdentityServer4.EntityFramework.DbContexts.PersistedGrantDbContext> options, OperationalStoreOptions storeOptions) : base(options, storeOptions)
    {
    }
}
```

I also had to add the DesignTimeFactories

```csharp
 public abstract class DesignTypeDbContextFactoryBase
    {
        protected IConfigurationRoot GetConfiguration()
        {
            var configuration = new ConfigurationBuilder()
               .SetBasePath(Directory.GetCurrentDirectory())
               .AddJsonFile("appsettings.json")
               .Build();

            return configuration;
        }
    }

    public class DesignConfigurationDbContextFactory : DesignTypeDbContextFactoryBase, IDesignTimeDbContextFactory<ConfigurationDbContext>
    {
        public ConfigurationDbContext CreateDbContext(string[] args)
        {
            var configuration = GetConfiguration();
            var builder = new DbContextOptionsBuilder<IdentityServer4.EntityFramework.DbContexts.ConfigurationDbContext>();
            var connectionString = configuration.GetConnectionString(nameof(SupportContext));
            builder.UseSqlServer(connectionString);

            return new ConfigurationDbContext(builder.Options, new ConfigurationStoreOptions());
        }
    }

    public class DesignPersistedGrantDbContextFactory : DesignTypeDbContextFactoryBase,
        IDesignTimeDbContextFactory<PersistedGrantDbContext>
    {

        public PersistedGrantDbContext CreateDbContext(string[] args)
        {
            var builder = new DbContextOptionsBuilder<IdentityServer4.EntityFramework.DbContexts.PersistedGrantDbContext>();
            var configuration = GetConfiguration();
            var connectionString = configuration.GetConnectionString(nameof(SupportContext));
            builder.UseSqlServer(connectionString);

            return new PersistedGrantDbContext(builder.Options, new OperationalStoreOptions());
        }
    }

```

Then I was able to able to create the migrations with the command

```powershell
Add-Migration InitialIdentityServerPersistedGrantDbMigration -Context PersistedGrantDbContext -OutputDir Migrations/IdentityServer/PersistedGrantDb -Project PathGuide.Support.DataAccess -v
```
```powershell
Add-Migration InitialIdentityServerConfigurationDbMigration -Context ConfigurationDbContext -OutputDir Migrations/IdentityServer/ConfigurationDb -Project PathGuide.Support.DataAccess -v
```

For some reason the Database.Migrate() function failed to create the tables? The reference is pointing to the correct  PersistedGrantDbContext.

However, I was able to create the tables by excuting

```powershell
Update-Database -Context ConfigurationDbContext 
Update-Database -Context PersistedGrantDbContext
```

**Comment by cbfrank** [comment]
I have the exactly same error. the solution I found is to comment the  ID4 database initialize code in Startup class temporarily,  because when the migration command runs, there haven't the database for ID4, so the ID4 db initialize code will throw exception.

**Comment by brockallen** [comment]
> the solution I found is to comment the ID4 database initialize code in Startup class temporarily

Yea, that's arguably not the best place to have put the "seed" code for the DB. If you leave that seed code in, then it will affect migrations (as that's a chicken and egg situation).

**Comment by scottbrady91** [comment]
FYI: This is only an issue if you have a method named `BuildWebHost` in Program.cs.

When you create a migration using the CLI, EF will look for this method and run your app. So if you're running migrations programmatically: boom.

Simple solution is to not have a method called `BuildWebHost`, and then everything works like normal.
